### ISSUE TITLE
Fix final phase of Mini-AutoML bundle

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1117]
The final phase of [Mini-AutoML Bundle](https://github.com/codalab/competition-examples/tree/master/codabench/mini-automl) returns this error:

```python
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
  File "/app/program/ingestion.py", line 79, in <module>
    main()
  File "/app/program/ingestion.py", line 62, in main
    m.fit(X_train, y_train)
  File "/app/output/model.py", line 20, in fit
    self.classifier.fit(X, y)
  File "/opt/conda/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 969, in fit
    super().fit(
  File "/opt/conda/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 210, in fit
    check_classification_targets(y)
  File "/opt/conda/lib/python3.9/site-packages/sklearn/utils/multiclass.py", line 200, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'
```

**Comment by Didayolo** [comment]
The problem most likely comes from the data

**Comment by Didayolo** [comment]
Done: https://github.com/codalab/competition-examples/commit/50e2bc461cbab31923d79efe3b4a9cdd2c871344
