### ISSUE TITLE
Certbot and Letsencrpyt

### ISSUE THREAD

**Issue by liviust** [codalab/codabench#1197]

**Comment by Didayolo** [comment]
It look like it should be here but it is missing:

https://github.com/codalab/codabench/wiki/How-to-deploy-Codabench-on-your-server#certbot-and-letsencrpyt

@dtuantran Any input on that?

**Comment by liviust** [comment]
Hi @Didayolo, @dtuantran, @ihsaan-ullah 

I have tried to secure minio db with let's encrypt. Everything works, except the compute worker. When I try to upload a submission, a get:

```python
I have tried to secure minio db with let's encrypt. The issue is that everything works, except the compute worker. When I try to upload a submission, a get:
`
django-1          | [2023-11-01 18:29:52 +0000] [13] [WARNING] Invalid HTTP request received.
django-1          | Traceback (most recent call last):
django-1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
django-1          |     self.parser.feed_data(data)
django-1          |   File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
django-1          | httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method
compute_worker-1  | [2023-11-01 18:29:52,800: WARNING/ForkPoolWorker-1] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /api/submissions/45/
django-1          | [2023-11-01 18:29:52 +0000] [13] [WARNING] Invalid HTTP request received.
django-1          | Traceback (most recent call last):
django-1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
django-1          |     self.parser.feed_data(data)
django-1          |   File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
django-1          | httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method
caddy-1           | 82.76.173.20 - - [01/Nov/2023:18:29:52 +0000] "GET /api/submissions/?phase__competition=1 HTTP/2.0" 200 1337
caddy-1           | 82.76.173.20 - - [01/Nov/2023:18:29:53 +0000] "GET /api/submissions/?phase=1 HTTP/2.0" 200 1025
caddy-1           | 82.76.173.20 - - [01/Nov/2023:18:29:53 +0000] "GET /api/phases/1/get_leaderboard/ HTTP/2.0" 200 639
minio-1           | 2023/11/01 18:29:54 http: TLS handshake error from 172.26.0.5:42025: EOF
compute_worker-1  | [2023-11-01 18:29:54,873: WARNING/ForkPoolWorker-1] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /api/submissions/45/
django-1          | [2023-11-01 18:29:54 +0000] [12] [WARNING] Invalid HTTP request received.
django-1          | Traceback (most recent call last):
django-1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
django-1          |     self.parser.feed_data(data)
django-1          |   File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
django-1          | httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method
compute_worker-1  | [2023-11-01 18:29:58,911: WARNING/ForkPoolWorker-1] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))': /api/submissions/45/
compute_worker-1  | [2023-11-01 18:29:58,947: INFO/ForkPoolWorker-1] CODALAB_IGNORE_CLEANUP_STEP mode enabled, ignoring clean up of: /codabench/tmpb79fsacz
django-1          | [2023-11-01 18:29:58 +0000] [12] [WARNING] Invalid HTTP request received.
django-1          | Traceback (most recent call last):
django-1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 165, in data_received
django-1          |     self.parser.feed_data(data)
django-1          |   File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
django-1          | httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method
compute_worker-1  | [2023-11-01 18:29:58,950: ERROR/ForkPoolWorker-1] Task compute_worker_run[01f513a8-6b3b-43bf-847e-a378bd1bced9] raised unexpected: SSLError(MaxRetryError("HTTPSConnectionPool(host='django', port=8000): Max retries exceeded with url: /api/submissions/45/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))"))
compute_worker-1  | Traceback (most recent call last):
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
compute_worker-1  |     httplib_response = self._make_request(conn, method, url,
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
compute_worker-1  |     self._validate_conn(conn)
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
compute_worker-1  |     conn.connect()
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 337, in connect
compute_worker-1  |     self.sock = ssl_wrap_socket(
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
compute_worker-1  |     return context.wrap_socket(sock, server_hostname=server_hostname)
compute_worker-1  |   File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
compute_worker-1  |     return self.sslsocket_class._create(
compute_worker-1  |   File "/usr/local/lib/python3.8/ssl.py", line 1073, in _create
compute_worker-1  |     self.do_handshake()
compute_worker-1  |   File "/usr/local/lib/python3.8/ssl.py", line 1342, in do_handshake
compute_worker-1  |     self._sslobj.do_handshake()
compute_worker-1  | ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)
compute_worker-1  |
compute_worker-1  | During handling of the above exception, another exception occurred:
compute_worker-1  |
compute_worker-1  | Traceback (most recent call last):
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
compute_worker-1  |     resp = conn.urlopen(
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen
compute_worker-1  |     return self.urlopen(method, url, body, headers, retries,
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen
compute_worker-1  |     return self.urlopen(method, url, body, headers, retries,
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen
compute_worker-1  |     return self.urlopen(method, url, body, headers, retries,
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
compute_worker-1  |     retries = retries.increment(method, url, error=e, _pool=self,
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
compute_worker-1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
compute_worker-1  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='django', port=8000): Max retries exceeded with url: /api/submissions/45/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))
compute_worker-1  |
compute_worker-1  | During handling of the above exception, another exception occurred:
compute_worker-1  |
compute_worker-1  | Traceback (most recent call last):
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
compute_worker-1  |     R = retval = fun(*args, **kwargs)
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
compute_worker-1  |     return self.run(*args, **kwargs)
compute_worker-1  |   File "/app/compute_worker.py", line 115, in run_wrapper
compute_worker-1  |     run.prepare()
compute_worker-1  |   File "/app/compute_worker.py", line 750, in prepare
compute_worker-1  |     self._update_status(STATUS_PREPARING)
compute_worker-1  |   File "/app/compute_worker.py", line 359, in _update_status
compute_worker-1  |     self._update_submission(data)
compute_worker-1  |   File "/app/compute_worker.py", line 337, in _update_submission
compute_worker-1  |     resp = self.requests_session.patch(url, data, timeout=150)
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in patch
compute_worker-1  |     return self.request('PATCH', url, data=data, **kwargs)
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 524, in request
compute_worker-1  |     resp = self.send(prep, **send_kwargs)
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 637, in send
compute_worker-1  |     r = adapter.send(request, **kwargs)
compute_worker-1  |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
compute_worker-1  |     raise SSLError(e, request=request)
compute_worker-1  | requests.exceptions.SSLError: HTTPSConnectionPool(host='django', port=8000): Max retries exceeded with url: /api/submissions/45/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))
`
``` 

Do you have any idea / solution for this?

**Comment by dtuantran** [comment]
> It look like it should be here but it is missing:
> 
> https://github.com/codalab/codabench/wiki/How-to-deploy-Codabench-on-your-server#certbot-and-letsencrpyt
> 
> @dtuantran Any input on that?

This doc is obsoleted. We use actually **caddy** as server proxy and this service manages automatically the certificate for **django**. About **minio**, by default, we don't use **HTTPS** for local installation.

If you need to secure your **minio**, you should install a reverse-proxy, e.g : Nginx, and create a valid SSL certificate. You can see more here: https://blog.min.io/minio-nginx-letsencrypt-certbot/

**Comment by dtuantran** [comment]
The doc is updated as : https://github.com/codalab/codabench/wiki/How-to-deploy-Codabench-on-your-server#securing-codabench-and-minio
