### ISSUE TITLE
Django crashes on a local installation

### ISSUE THREAD

**Issue by liviust** [codalab/codabench#1201]
I'm testing the platform and I keep getting the bellow error on the current develop branch:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/app/src/apps/pages/views.py", line 19, in get_context_data
    data = Competition.objects.aggregate(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 379, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 489, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "competitions_competition" does not exist
LINE 1: ...."published" = false) AS "unpublished_comps" FROM "competiti...
                                                             ^
```

The site-worker returned:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "competitions_phase" does not exist
LINE 1: UPDATE "competitions_phase" SET "status" = CASE WHEN ("compe...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/src/apps/competitions/tasks.py", line 673, in do_phase_migrations
    Phase.objects.annotate(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 741, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1471, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "competitions_phase" does not exist
LINE 1: UPDATE "competitions_phase" SET "status" = CASE WHEN ("compe...
```

The installation was conducted on an Azure virtual machine with nginx (as there is no caddy doc available yet on how to secure both codabench and minio). The storage is set to minio and the .env is set for production:

I have uploaded the example iris bundle and submitted the example run several times. Everything works fine. I have also tested various features of the platform with no errors. The server operates for an arbitrary period of time. Then the error mentioned above appears without any action being performed. I just let it run for 20 hours and found it with this error. No specific actions were taken on the user's part as well.

`docker ps -a`

```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED        STATUS                    PORTS
                                                                                       NAMES
11a785a294b0    codabench-compute_worker      "bash -c 'watchmedo …"   20 hours ago   Up 20 hours
                                                                                        codabench-compute_worker-1
8a306a08f593   abiosoft/caddy:1.0.3                       "/bin/parent caddy -…"   20 hours ago   Up 20 hours               0.0.0.0:81->81/tcp, :::81->81/tcp, 80/tcp, 2015/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                             codabench-caddy-1
12a8ed583b65    codabench-django              "bash -c 'cd /app/sr…"   20 hours ago   Up 20 hours               0.0.0.0:8000->8000/tcp, :::8000->8000/tcp
                                                                                        codabench-django-1
8a1b24bc311b   minio/mc                                   "/bin/sh -c ' set -x…"   20 hours ago   Exited (0) 20 hours ago
                                                                                        codabench-createbuckets-1
fd6ea370387e    codabench-site_worker         "bash -c 'watchmedo …"   20 hours ago   Up 20 hours
                                                                                        codabench-site_worker-1
4af4c9ad80cd    codabench-flower              "flower"                 20 hours ago   Up 20 hours               0.0.0.0:5555->5555/tcp, :::5555->5555/tcp
                                                                                        codabench-flower-1
070f598d3931    codabench-builder             "docker-entrypoint.s…"   20 hours ago   Up 20 hours
                                                                                        codabench-builder-1
0029ce5c5999   minio/minio:RELEASE.2020-10-03T02-19-42Z   "/usr/bin/docker-ent…"   20 hours ago   Up 20 hours (healthy)     0.0.0.0:9000->9000/tcp, :::9000->9000/tcp
                                                                                        codabench-minio-1
7dc20211d32a   redis                                      "docker-entrypoint.s…"   20 hours ago   Up 20 hours               0.0.0.0:6379->6379/tcp, :::6379->6379/tcp
                                                                                        codabench-redis-1
a485906b2238    codabench-rabbit              "docker-entrypoint.s…"   20 hours ago   Up 20 hours               4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp    codabench-rabbit-1
5e2b817aacb7   postgres:12-alpine                         "docker-entrypoint.s…"   20 hours ago   Up 20 hours               0.0.0.0:5432->5432/tcp, :::5432->5432/tcp
                                                                                        codabench-db-1
```

I want to use this local installation for my students to submit their runs for simple ML tasks. The only way to fix the issue is to reset the database, which is not ideal. Once the students submit their runs, I cannot reset it because I would lose their submissions, and they would have to register again each time I reset the database.

Is there a way to fix this properly?

**Comment by Didayolo** [comment]
This looks like a Django migration problem. What happens when you run the following command?

```sh
docker-compose exec django ./manage.py migrate
```

**Comment by ihsaan-ullah** [comment]
@liviust 
Closing this issue for now. Feel free to open it if you are still facing the issue after running the command mentioned by Adrien.
