### ISSUE TITLE
Docker pull fails  + wrong status

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1203]
It looks like almost every 3rd submission fails because of this docker pull failure. Example below:

```
Pull for image: ihsaanullah/fair-universe:new returned a non-zero exit code! Check if the docker image exists on docker hub.
```

Additional problem: When this happens, instead of the status to be `Failed` it says scoring

**Comment by Didayolo** [comment]
What queue are you using?

**Comment by ihsaan-ullah** [comment]
> What queue are you using?

default queue

**Comment by ihsaan-ullah** [comment]
Competition link: https://www.codabench.org/competitions/1299/

**Comment by ihsaan-ullah** [comment]
Sometimes the docker pull fails in preparing status and the status is not changed to failed

**Comment by ihsaan-ullah** [comment]
all these are stuck 
<img width="1055" alt="Screenshot 2023-10-31 at 8 11 28 PM" src="https://github.com/codalab/codabench/assets/13259262/e06f642b-0305-48be-b436-c9c3cdcc5868">

**Comment by Didayolo** [comment]
Some logs:

```python
[2023-10-31 13:02:06,485: INFO/ForkPoolWorker-11] Destroying submission temp dir: /codabench/tmpreln2mby
[2023-10-31 13:02:06,490: ERROR/ForkPoolWorker-11] Task compute_worker_run[d827f689-4c42-4076-aec0-abf41897e711] raised unexpected: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='www.codabench.org', port=443): Max retries exceeded with url: /api/submissions/28133/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2be400dd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f2be400dd00>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 663, in urlopen
    return self.urlopen(method, url, body, headers, retries,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.codabench.org', port=443): Max retries exceeded with url: /api/submissions/28133/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2be400dd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/compute_worker.py", line 115, in run_wrapper
    run.prepare()
  File "/compute_worker.py", line 750, in prepare
    self._update_status(STATUS_PREPARING)
  File "/compute_worker.py", line 359, in _update_status
    self._update_submission(data)
  File "/compute_worker.py", line 337, in _update_submission
    resp = self.requests_session.patch(url, data, timeout=150)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 596, in patch
    return self.request('PATCH', url, data=data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.codabench.org', port=443): Max retries exceeded with url: /api/submissions/28133/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2be400dd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-10-31 13:42:55,252: INFO/MainProcess] Received task: compute_worker_run[2d45de67-aee4-4b99-b6de-16b21f951882]  
[2023-10-31 13:42:55,257: INFO/ForkPoolWorker-11] Received run arguments: {'user_pk': 977, 'submissions_api_url': 'https://www.codabench.org/api', 'secret': 'c886d704-9227-4346-996e-354252f5c6f0', 'docker_image': 'codalab/codalab-legacy:py37', 'execution_time_limit': 600, 'id': 28137, 'is_scoring': False, 'prediction_result': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/prediction_result/2023-10-31-1698759666/fd866829bc3b/prediction_result.zip?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=p4o76rTEVGALHkx7BHya%2BU0m6J0%3D&content-type=application%2Fzip&Expires=1698846066', 'ingestion_only_during_scoring': False, 'program_data': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/dataset/2023-10-31-1698759665/814b9faeebf0/results.zip?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=U8jncPN1AXGar1CAnmY3joyUfCU%3D&Expires=1698846066', 'prediction_stdout': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/submission_details/2023-10-31-1698759666/34210f2f9a0d/prediction_stdout.txt?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=%2F5rD%2BOar%2FyrRzT0Mso4qJSNstFc%3D&content-type=application%2Fzip&Expires=1698846066', 'prediction_stderr': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/submission_details/2023-10-31-1698759666/1f9a298c25eb/prediction_stderr.txt?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=QjP9xch3Mx1Foy0jOL6ZT%2BBoKxw%3D&content-type=application%2Fzip&Expires=1698846066', 'prediction_ingestion_stdout': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/submission_details/2023-10-31-1698759666/28b3b135997e/prediction_ingestion_stdout.txt?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=W9e2ycAg5xOHmP3QU2ewR2nnpSU%3D&content-type=application%2Fzip&Expires=1698846066', 'prediction_ingestion_stderr': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/submission_details/2023-10-31-1698759666/5ca5d06ad629/prediction_ingestion_stderr.txt?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=sqXbpK4k3yMuiCUVEtoogzY0cm4%3D&content-type=application%2Fzip&Expires=1698846066'}
[2023-10-31 13:42:55,259: INFO/ForkPoolWorker-11] Updating submission @ https://www.codabench.org/api/submissions/28137/ with data = {'status': 'Preparing', 'status_details': None, 'secret': 'c886d704-9227-4346-996e-354252f5c6f0'}
```

**Comment by Didayolo** [comment]
The docker pull fails is specific to one worker. We stopped it.

**Comment by ihsaan-ullah** [comment]
If a submission fails in ingestion, it should have `failed` status. Then if it fails in scoring, we should have the same `failed` status with logs in the logs file. 

But the logs above shows another issue of connection I think `_update_submission_` should be wrapped in try catch to avoid the crash

**Comment by Didayolo** [comment]
Let's keep track of it here: #1205
