### ISSUE TITLE
Server Error (500) when updating submission

### ISSUE THREAD

**Issue by TGoldsack1** [codalab/codabench#1269]
Hello,

I am currently in the process of setting up a competition on CodaBench, hoping to publish it in the next week.

I am having some trouble with the compute worker for processing submissions to my competition. I had successfully set my worker up, and yesterday it was working fine. However, today after making some minor adjustments to my scoring program, competition bundle, and competition docker image, my compute worker is getting an Internal Server error 500 when updating the status of a submission. This causes my submission to be stuck on "Submitted" and my compute worker program to crash.

Below is a snippet of the Docker logs of my compute worker where the error occurs (with the secret replaced with "x"):

```
[2024-01-10 14:59:11,680: INFO/ForkPoolWorker-1] Updating submission @ https://www.codabench.org/api/submissions/35352/ with data = {'status': 'Preparing', 'status_details': None, 'secret': 'x'}
[2024-01-10 14:59:11,851: INFO/ForkPoolWorker-1] Submission patch failed with status = 500, and response = 
b'<h1>Server Error (500)</h1>'
[2024-01-10 14:59:11,851: INFO/ForkPoolWorker-1] Updating submission @ https://www.codabench.org/api/submissions/35352/ with data = {'status': 'Failed', 'status_details': 'Failure updating submission data.', 'secret': 'x'}
[2024-01-10 14:59:11,911: INFO/ForkPoolWorker-1] Submission patch failed with status = 500, and response = 
b'<h1>Server Error (500)</h1>'
[2024-01-10 14:59:11,912: INFO/ForkPoolWorker-1] Destroying submission temp dir: /codabench/tmp1uzj5qds
[2024-01-10 14:59:11,914: ERROR/ForkPoolWorker-1] Task compute_worker_run[d8212377-f9cb-4255-b8ea-02033a3bed52] raised unexpected: SubmissionException('Failure updating submission data.')
Traceback (most recent call last):
  File "/compute_worker.py", line 115, in run_wrapper
    run.prepare()
  File "/compute_worker.py", line 752, in prepare
    self._update_status(STATUS_PREPARING)
  File "/compute_worker.py", line 359, in _update_status
    self._update_submission(data)
  File "/compute_worker.py", line 342, in _update_submission
    raise SubmissionException("Failure updating submission data.")
compute_worker.SubmissionException: Failure updating submission data.

During handling of the above exception, another exception occurred:
```

Is there any way to determine what might be causing this error? 

Thanks,
Tomas

**Comment by ihsaan-ullah** [comment]
Hi Tomas,

To debug this, can you try the following:

- use the default compute worker in your competition and run a submission
To do this, make this field empty
<img width="862" alt="Screenshot 2024-01-10 at 8 14 43 PM" src="https://github.com/codalab/codabench/assets/13259262/f2d4f6b2-7653-4058-b32c-09c2f5e0a62c">

- Try calling the update submission API `https://www.codabench.org/api/submissions/SUBMISSION_ID` using Postman or some other tool. Do not forget to check the API documentation: https://www.codabench.org/api/docs/

**Comment by TGoldsack1** [comment]
Thanks for your quick response! 

I followed your suggestions - my submission on the default worker also remains in the "Submitted" phase. When I try and update the submission using Postman, I get a 403 "Submission secrets do not match" error, but I may have been doing this incorrectly - can you confirm where I can find the correct submission secret? I could not find any info on this in the documentation.

Also, I noticed that #1270 (also posted yesterday) appears to be experiencing the same issue - is it possible that this is being caused by an issue on CodaBench servers?

**Comment by ihsaan-ullah** [comment]
@TGoldsack1 we have restarted our service and the problem is solved, please check and report if you have any more issues.
