### ISSUE TITLE
All the submission stuck in "submitted" phase

### ISSUE THREAD

**Issue by starsholic** [codalab/codabench#1302]
Hi, @ihsaan-ullah @Didayolo 

We have organized a competition at https://www.codabench.org/competitions/1772. However, we've encountered an issue since 26th where all submissions remain in the "submitted" phase for several hours without progressing. This issue persists currently. We have attempted to resubmit multiple times, but the problem continues. Could you help us check it?

Thanks

**Comment by starsholic** [comment]
Since our competition Phase 1 will be ended soon (1.30th), the situation is quite emergent...

**Comment by Didayolo** [comment]
```python
django_1          | [2024-01-29 08:19:40 +0000] [13] [ERROR] Exception in ASGI application
django_1          | Traceback (most recent call last):
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 157, in run_asgi
django_1          |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
django_1          |     return await self.app(scope, receive, send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
django_1          |     await instance(receive, send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/sessions.py", line 183, in __call__
django_1          |     return await self.inner(receive, self.send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/middleware.py", line 41, in coroutine_call
django_1          |     await inner_instance(receive, send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 58, in __call__
django_1          |     await await_many_dispatch(
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
django_1          |     await dispatch(result)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 73, in dispatch
django_1          |     await handler(message)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
django_1          |     await self.disconnect(message["code"])
django_1          |   File "/app/src/apps/competitions/consumers.py", line 65, in disconnect
django_1          |     await self.close()
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/generic/websocket.py", line 226, in close
django_1          |     await super().send({"type": "websocket.close"})
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 81, in send
django_1          |     await self.base_send(message)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/sessions.py", line 236, in send
django_1          |     return await self.real_send(message)
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 234, in asgi_send
django_1          |     raise RuntimeError(msg % message_type)
django_1          | RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
```

**Comment by Didayolo** [comment]
@ihsaan-ullah @starsholic 

After restarting the service, the problem seems to be solved.

However the error log above is still present.

**Comment by acletournel** [comment]
I have just restarted the docker stack. It works again.

**Comment by starsholic** [comment]
Thank you very much!
