### ISSUE TITLE
Remote workers not receiving submissions (private queue)

### ISSUE THREAD

**Issue by johanneskruse** [codalab/codabench#1473]
Hi, 

I'm running a competition and my remote workers has stopped receving any submissions. 

<img width="868" alt="image" src="https://github.com/codalab/codabench/assets/43001334/8061790f-fb37-499c-832d-0667e1eaec84">

I don't have any error logs from them. I might be related to #1446.

Best,
Johannes

**Comment by johanneskruse** [comment]
The public queue seems to be working; but I cannot use it for our competition because of the run time limit.

**Comment by johanneskruse** [comment]
I am now getting the following output when running ```docker logs -f compute_worker```:

```
[2024-06-09 18:42:40,185: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/usr/local/lib/python3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2024-06-09 18:42:41,321: ERROR/MainProcess] consumer: Cannot connect to amqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:**@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp%3A//63a35e45-cb28-4eed-9c2c-af8072bf9d9c%3Ad9506f3c-afe6-4824-baef-dc3c7e7fe80b%40www.codabench.org%3A5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c: Connection.open: (530) NOT_ALLOWED - vhost 4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:d9506f3c-afe6-4824-baef-dc3c7e7fe80b@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c not found.
Trying to reconnect...

[2024-06-09 18:42:41,465: ERROR/MainProcess] consumer: Cannot connect to amqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:**@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp%3A//63a35e45-cb28-4eed-9c2c-af8072bf9d9c%3Ad9506f3c-afe6-4824-baef-dc3c7e7fe80b%40www.codabench.org%3A5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c: Connection.open: (530) NOT_ALLOWED - vhost 4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:d9506f3c-afe6-4824-baef-dc3c7e7fe80b@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c not found.
Trying to reconnect...

[2024-06-09 18:42:41,613: ERROR/MainProcess] consumer: Cannot connect to amqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:**@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp%3A//63a35e45-cb28-4eed-9c2c-af8072bf9d9c%3Ad9506f3c-afe6-4824-baef-dc3c7e7fe80b%40www.codabench.org%3A5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c: Connection.open: (530) NOT_ALLOWED - vhost 4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:d9506f3c-afe6-4824-baef-dc3c7e7fe80b@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c not found.
Trying to reconnect...

[2024-06-09 18:42:41,769: ERROR/MainProcess] consumer: Cannot connect to amqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:**@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp%3A//63a35e45-cb28-4eed-9c2c-af8072bf9d9c%3Ad9506f3c-afe6-4824-baef-dc3c7e7fe80b%40www.codabench.org%3A5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c: Connection.open: (530) NOT_ALLOWED - vhost 4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:d9506f3c-afe6-4824-baef-dc3c7e7fe80b@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c not found.
Trying to reconnect...

[2024-06-09 18:42:41,903: ERROR/MainProcess] consumer: Cannot connect to amqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:**@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp%3A//63a35e45-cb28-4eed-9c2c-af8072bf9d9c%3Ad9506f3c-afe6-4824-baef-dc3c7e7fe80b%40www.codabench.org%3A5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c: Connection.open: (530) NOT_ALLOWED - vhost 4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:d9506f3c-afe6-4824-baef-dc3c7e7fe80b@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c not found.
Trying to reconnect...

[2024-06-09 18:42:42,041: ERROR/MainProcess] consumer: Cannot connect to amqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:**@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp%3A//63a35e45-cb28-4eed-9c2c-af8072bf9d9c%3Ad9506f3c-afe6-4824-baef-dc3c7e7fe80b%40www.codabench.org%3A5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c: Connection.open: (530) NOT_ALLOWED - vhost 4d4c54a3-6e7f-418a-8d6b-36345ea8b37cpyamqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:d9506f3c-afe6-4824-baef-dc3c7e7fe80b@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c not found.
Trying to reconnect...
```

**Comment by johanneskruse** [comment]
I then tried using an old queue, which have previously been working:

```
[2024-06-09 18:59:15,558: INFO/MainProcess] Connected to amqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:**@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c
[2024-06-09 18:59:15,684: INFO/MainProcess] mingle: searching for neighbors
[2024-06-09 18:59:17,057: INFO/MainProcess] mingle: all alone
[2024-06-09 18:59:17,148: CRITICAL/MainProcess] Unrecoverable error: PreconditionFailed(406, "PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'compute-worker' in vhost '4d4c54a3-6e7f-418a-8d6b-36345ea8b37c': received the value '10' of type 'signedint' but current is none", (50, 10), 'Queue.declare')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/tasks.py", line 40, in start
    c.task_consumer = c.app.amqp.TaskConsumer(
  File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 301, in TaskConsumer
    return self.Consumer(
  File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 408, in revive
    self.declare()
  File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 421, in declare
    queue.declare()
  File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 611, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 620, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 648, in queue_declare
    ret = channel.queue_declare(
  File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 1148, in queue_declare
    return queue_declare_ok_t(*self.wait(
  File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.8/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 520, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 279, in _on_close
    raise error_for_code(
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'compute-worker' in vhost '4d4c54a3-6e7f-418a-8d6b-36345ea8b37c': received the value '10' of type 'signedint' but current is none
```

**Comment by johanneskruse** [comment]
I am now getting the following output logs:

```
$ docker logs -f compute_worker
/usr/local/lib/python3.8/site-packages/celery/platforms.py:800: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
 
 -------------- compute-worker@efe5103be5d4 v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-5.15.0-1062-aws-x86_64-with-glibc2.34 2024-06-09 19:02:33
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7f7a65017a30
- ** ---------- .> transport:   amqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:**@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> compute-worker   exchange=compute-worker(direct) key=compute-worker
                

[tasks]
  . compute_worker_run

[2024-06-09 19:02:33,405: INFO/MainProcess] Connected to amqp://63a35e45-cb28-4eed-9c2c-af8072bf9d9c:**@www.codabench.org:5672/4d4c54a3-6e7f-418a-8d6b-36345ea8b37c
[2024-06-09 19:02:33,523: INFO/MainProcess] mingle: searching for neighbors
[2024-06-09 19:02:34,879: INFO/MainProcess] mingle: all alone
[2024-06-09 19:02:35,079: CRITICAL/MainProcess] Unrecoverable error: PreconditionFailed(406, "PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'compute-worker' in vhost '4d4c54a3-6e7f-418a-8d6b-36345ea8b37c': received the value '10' of type 'signedint' but current is none", (50, 10), 'Queue.declare')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/tasks.py", line 40, in start
    c.task_consumer = c.app.amqp.TaskConsumer(
  File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 301, in TaskConsumer
    return self.Consumer(
  File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 386, in __init__
    self.revive(self.channel)
  File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 408, in revive
    self.declare()
  File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 421, in declare
    queue.declare()
  File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 611, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 620, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 648, in queue_declare
    ret = channel.queue_declare(
  File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 1148, in queue_declare
    return queue_declare_ok_t(*self.wait(
  File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.8/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 520, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 279, in _on_close
    raise error_for_code(
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'compute-worker' in vhost '4d4c54a3-6e7f-418a-8d6b-36345ea8b37c': received the value '10' of type 'signedint' but current is none
```

**Comment by Didayolo** [comment]
Hi,

It seems to be a general problem. I am not able to compute submissions on my custom queue.

The difference is that I just have not logs in my case.

**Comment by Didayolo** [comment]
@ObadaS Do you think this problem is happening since the upgrade of Caddy?

It is a very concerning issue, we need to solve it asap.

**Comment by ObadaS** [comment]
> @ObadaS Do you think this problem is happening since the upgrade of Caddy?

Caddy is not used for workers since it only supports the HTTP(s) protocol and not AMQP that RabbitMQ uses, so I don't think it's connected to the Caddy upgrade

**Comment by ObadaS** [comment]
@johanneskruse Hello, have you tried creating a new worker on a fresh machine/virtual machine?

Also, just to make sure, you are using this command to launch the worker, without changing anything ?

```
docker run \
    -v /codabench:/codabench \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -d \
    --env-file .env \
    --name compute_worker \
    --restart unless-stopped \
    --log-opt max-size=50m \
    --log-opt max-file=3 \
    codalab/competitions-v2-compute-worker:latest 
```

**Comment by Didayolo** [comment]
@ObadaS I attached the worker wk8 to a custom queue named "TMP", and I confirm this is not working

**Comment by ObadaS** [comment]
@johanneskruse The problem should be fixed.

@Didayolo I got some logs that we can analyze later for this weird problem. I tried restarting the RabbitMQ container alone, but it did not fix the problem. It only got fixed after I restart all the containers (but I suspect that the problem might be coming from the site_worker container, we can try restarting it only, if the problem happens again in the future)

**Comment by johanneskruse** [comment]
@ObadaS - I can confirm that it is indeed working on my end.

Thank you both for your swift actions!

**Comment by johanneskruse** [comment]
Hi @Didayolo and @ObadaS. 

The remote workers are now receiving jobs and running; however, before, a job was finished within 3-4 hours. Now jobs are running for more than 8 hours, and some haven't even stopped yet. Nothing has changed on my end. Is there any explanation or something that might fix this?

**Comment by Didayolo** [comment]
That is weird indeed. I haven't notice any difference on my side (another queue and competition).

**Comment by johanneskruse** [comment]
Yes, it is very strange. I've previously been able to run four remote workers per instance, but I've had to lower the number as it has started to consume more CPU utilization.

Furthermore, some submissions complete, some run forever, and some fail due to:

<img width="210" alt="Screenshot 2024-06-12 at 08 52 12" src="https://github.com/codalab/codabench/assets/43001334/ae3ebc5f-b735-4591-a1a6-1cbfb0f05d58">

**Comment by johanneskruse** [comment]
Hi @Didayolo and @ObadaS, 

The remote workers have again stopped receiving jobs. This is the third week in a row it happens around the same time of the week. I'm not sure if it is a coincidence or if there is something more systematic about the timing of the issue.

<img width="716" alt="Screenshot 2024-06-14 at 22 35 01" src="https://github.com/codalab/codabench/assets/43001334/13d122e5-dd15-4321-ac95-7ee0e75b4e0f">

**Comment by johanneskruse** [comment]
Systems are still down

**Comment by jpbrunetsx** [comment]
Hi all, 
Same problem since about friday 5pm (CET) on our competition/private workers. 

We also have something similar as what is described here as "long running time" where the status is not updated for very long after scoring is finished and submission is displayed as "running" (but this is not a consistent issue and would need a more in depth look on our end).

**Comment by Didayolo** [comment]
> Systems are still down on my end

Coming back from week-end, I'll try to get some logs to make progress on the issue, then restart the service.

**Comment by Didayolo** [comment]
```python
codabench-caddy-1          | 2024/06/17 07:25:35.888	ERROR	http.log.access.log0	handled request	{"request": {"remote_ip": "129.175.8.21", "remote_port": "57760", "client_ip": "129.175.8.21", "proto": "HTTP/1.1", "method": "GET", "host": "www.codabench.org", "uri": "/submission_output/", "headers": {"Origin": ["https://www.codabench.org"], "X-Forwarded-Proto": ["wss"], "Connection": ["Upgrade"], "Cookie": [], "Sec-Websocket-Version": ["13"], "X-Forwarded-Server": ["02dfc7840419"], "User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"], "Accept-Encoding": ["gzip, deflate, br, zstd"], "Cache-Control": ["no-cache"], "Sec-Websocket-Extensions": ["permessage-deflate; client_max_window_bits"], "X-Forwarded-For": ["154.178.176.10"], "X-Forwarded-Port": ["443"], "X-Real-Ip": ["154.178.176.10"], "X-Forwarded-Host": ["www.codabench.org"], "Accept-Language": ["en-US,en;q=0.9"], "Pragma": ["no-cache"], "Sec-Websocket-Key": ["l88AD5IfsEn+5eAS4XyPEA=="], "Upgrade": ["websocket"]}}, "bytes_read": 0, "user_id": "", "duration": 0.007179748, "size": 0, "status": 403, "resp_headers": {"Content-Type": ["text/plain"], "Date": ["Mon, 17 Jun 2024 07:25:35 GMT"], "Content-Length": ["0"]}}
```

```python
codabench-caddy-1          | 2024/06/17 07:25:11.905	ERROR	http.log.access.log0	handled request	{"request": {"remote_ip": "129.175.8.21", "remote_port": "57760", "client_ip": "129.175.8.21", "proto": "HTTP/1.1", "method": "GET", "host": "www.codabench.org", "uri": "/submission_output/", "headers": {"Cookie": [], "X-Real-Ip": ["154.178.176.10"], "Accept-Encoding": ["gzip, deflate, br, zstd"], "Sec-Websocket-Version": ["13"], "X-Forwarded-For": ["154.178.176.10"], "X-Forwarded-Host": ["www.codabench.org"], "Pragma": ["no-cache"], "Accept-Language": ["en-US,en;q=0.9"], "Sec-Websocket-Extensions": ["permessage-deflate; client_max_window_bits"], "Upgrade": ["websocket"], "X-Forwarded-Port": ["443"], "Cache-Control": ["no-cache"], "Connection": ["Upgrade"], "Origin": ["https://www.codabench.org"], "Sec-Websocket-Key": ["wkZYbRNKsIevR63IG0R+iQ=="], "X-Forwarded-Proto": ["wss"], "X-Forwarded-Server": ["02dfc7840419"], "User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"]}}, "bytes_read": 0, "user_id": "", "duration": 0.009992954, "size": 0, "status": 403, "resp_headers": {"Content-Length": ["0"], "Content-Type": ["text/plain"], "Date": ["Mon, 17 Jun 2024 07:25:11 GMT"]}}
```

```python
codabench-django-1         | [2024-06-17 07:25:11 +0000] [11] [ERROR] Exception in ASGI application
codabench-django-1         | Traceback (most recent call last):
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 157, in run_asgi
codabench-django-1         |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
codabench-django-1         |     return await self.app(scope, receive, send)
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
codabench-django-1         |     await instance(receive, send)
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/channels/sessions.py", line 183, in __call__
codabench-django-1         |     return await self.inner(receive, self.send)
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/channels/middleware.py", line 41, in coroutine_call
codabench-django-1         |     await inner_instance(receive, send)
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 58, in __call__
codabench-django-1         |     await await_many_dispatch(
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
codabench-django-1         |     await dispatch(result)
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 73, in dispatch
codabench-django-1         |     await handler(message)
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
codabench-django-1         |     await self.disconnect(message["code"])
codabench-django-1         |   File "/app/src/apps/competitions/consumers.py", line 65, in disconnect
codabench-django-1         |     await self.close()
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/channels/generic/websocket.py", line 226, in close
codabench-django-1         |     await super().send({"type": "websocket.close"})
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 81, in send
codabench-django-1         |     await self.base_send(message)
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/channels/sessions.py", line 236, in send
codabench-django-1         |     return await self.real_send(message)
codabench-django-1         |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 234, in asgi_send
codabench-django-1         |     raise RuntimeError(msg % message_type)
codabench-django-1         | RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
codabench-django-1         | [2024-06-17 07:25:12 +0000] [12] [INFO] ('192.168.48.7', 54656) - "WebSocket /submission_output/" 403
```

**Comment by ObadaS** [comment]
@Didayolo I don't think this is a Caddy problem. Those errors don't seem to have anything to do with this problem. I think the problem comes from the site_worker container.

```
codabench-site_worker-1  | [2024-06-17 05:36:48,866: ERROR/ForkPoolWorker-2] Task competitions.tasks._run_submission[...] raised unexpected: PreconditionFailed(406, "PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'compute-worker' in vhost '988f0756-7c60-40e6-9e6b-40d830125d83': received none but current is the value '10' of type 'signedint'", (50, 10), 'Queue.declare')
codabench-site_worker-1  | Traceback (most recent call last):
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
codabench-site_worker-1  |     R = retval = fun(*args, **kwargs)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
codabench-site_worker-1  |     return self.run(*args, **kwargs)
codabench-site_worker-1  |   File "/app/src/apps/competitions/tasks.py", line 318, in _run_submission
codabench-site_worker-1  |     _send_to_compute_worker(submission, is_scoring)
codabench-site_worker-1  |   File "/app/src/apps/competitions/tasks.py", line 199, in _send_to_compute_worker
codabench-site_worker-1  |     task = celery_app.send_task(
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 745, in send_task
codabench-site_worker-1  |     amqp.send_task_message(P, name, message, **options)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 543, in send_task_message
codabench-site_worker-1  |     ret = producer.publish(
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 178, in publish
codabench-site_worker-1  |     return _publish(
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 533, in _ensured
codabench-site_worker-1  |     return fun(*args, **kwargs)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 194, in _publish
codabench-site_worker-1  |     [maybe_declare(entity) for entity in declare]
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 194, in <listcomp>
codabench-site_worker-1  |     [maybe_declare(entity) for entity in declare]
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 102, in maybe_declare
codabench-site_worker-1  |     return maybe_declare(entity, self.channel, retry, **retry_policy)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/common.py", line 121, in maybe_declare
codabench-site_worker-1  |     return _maybe_declare(entity, channel)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/common.py", line 161, in _maybe_declare
codabench-site_worker-1  |     entity.declare(channel=channel)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 611, in declare
codabench-site_worker-1  |     self._create_queue(nowait=nowait, channel=channel)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 620, in _create_queue
codabench-site_worker-1  |     self.queue_declare(nowait=nowait, passive=False, channel=channel)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/kombu/entity.py", line 648, in queue_declare
codabench-site_worker-1  |     ret = channel.queue_declare(
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 1148, in queue_declare
codabench-site_worker-1  |     return queue_declare_ok_t(*self.wait(
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 88, in wait
codabench-site_worker-1  |     self.connection.drain_events(timeout=timeout)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 508, in drain_events
codabench-site_worker-1  |     while not self.blocking_read(timeout):
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 514, in blocking_read
codabench-site_worker-1  |     return self.on_inbound_frame(frame)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/method_framing.py", line 55, in on_frame
codabench-site_worker-1  |     callback(channel, method_sig, buf, None)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 520, in on_inbound_method
codabench-site_worker-1  |     return self.channels[channel_id].dispatch_method(
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
codabench-site_worker-1  |     listener(*args)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 279, in _on_close
codabench-site_worker-1  |     raise error_for_code(
codabench-site_worker-1  | amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'compute-worker' in vhost '988f0756-7c60-40e6-9e6b-40d830125d83': received none but current is the value '10' of type 'signedint'
```

Caddy does not redirect the requests to RabbitMQ since it does not support other protocols than HTTP(S).
It also seems like restarting the site_worker might fix the issue temporarily, which makes it even less likely that the problem comes from Caddy.

**Comment by Didayolo** [comment]
Ah yes that is what we wanted to try. I couldn't remember and did not wanted to let the queue blocked for too much time. Thank you very much for you input.

**Comment by johanneskruse** [comment]
It is running again after the reset - thank you!

**Comment by Didayolo** [comment]
@johanneskruse May I ask how many workers you have on your private queue?

Apart from the bug reported above, it seems that your queue does not have enough resources to handle the load of your competition.

**Comment by johanneskruse** [comment]
@Didayolo - the competition is coming to an end and we are experiencing a high-level of submissions.

At the moment we 20 workers; but I can see a few of them have crashed and I have to reset them. Is there a limit on amount of workers?

**Comment by xbaro** [comment]
According to this issue [https://github.com/amqp-node/amqplib/issues/165](https://github.com/amqp-node/amqplib/issues/165), the error:

```bash
codabench-site_worker-1  | [2024-06-17 05:36:48,866: ERROR/ForkPoolWorker-2] Task competitions.tasks._run_submission[...] 
...
codabench-site_worker-1  |     listener(*args)
codabench-site_worker-1  |   File "/usr/local/lib/python3.8/site-packages/amqp/channel.py", line 279, in _on_close
codabench-site_worker-1  |     raise error_for_code(
codabench-site_worker-1  | amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'compute-worker' in vhost '988f0756-7c60-40e6-9e6b-40d830125d83': received none but current is the value '10' of type 'signedint'
```

from @Didayolo [logs ](https://github.com/codalab/codabench/issues/1473#issuecomment-2172530347) is due to a change in the queue configuration.

It seems that at some point the queue is created with 'x-max-priority=10', but at some latter moment is defined without this maximum priority value.  

Does it have sense to you?

**Comment by Didayolo** [comment]
> Is there a limit on amount of workers?

@johanneskruse : No, there is not limit.

> It seems that at some point the queue is created with 'x-max-priority=10', but at some latter moment is defined without this maximum priority value.

@xbaro : yes, I've seen this explanation. However, everywhere in the code we set this value to 10, I don't know how exactly sometimes it receives a value of `None`.

**Comment by johanneskruse** [comment]
@Didayolo, @ObadaS - The remote workers seems to have lost connection again.

**Comment by Didayolo** [comment]
@johanneskruse Done.

Interesting investigation of this problem here:

https://github.com/codalab/codabench/pull/1352#issuecomment-2155250806

- #1352

**Comment by johanneskruse** [comment]
@Didayolo - workers seem to be disconnected.

**Comment by ObadaS** [comment]
@johanneskruse Hello, I fixed it for now.

**Comment by Didayolo** [comment]
@johanneskruse Hi, the good news is that we found a fix! We will deploy it soon in production.

**Comment by johanneskruse** [comment]
@ObadaS - Thanks! I can confirm that they are running.
@Didayolo - Exciting, great job all of you and thanks for your continued support and improvements!
