### ISSUE TITLE
'file_size' KeyError at /api/datasets/

### ISSUE THREAD

**Issue by liviust** [codalab/codabench#1474]
There seems to be an error with the datasets 'file_size' Key, both in develop and master branches. It triggers when uploading a bundle competition.

```
2024-06-09 09:58:59 django-1          | Internal Server Error: /api/datasets/
2024-06-09 09:58:59 django-1          | Traceback (most recent call last):
2024-06-09 09:58:59 django-1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272506+00:00 [info] <0.254.0> Running boot step rabbit_exchange_type_headers defined by app rabbit
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272605+00:00 [info] <0.254.0> Running boot step rabbit_exchange_type_topic defined by app rabbit
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272658+00:00 [info] <0.254.0> Running boot step rabbit_mirror_queue_mode_all defined by app rabbit
2024-06-09 09:58:59 django-1          |     response = get_response(request)
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272684+00:00 [info] <0.254.0> Running boot step rabbit_mirror_queue_mode_exactly defined by app rabbit
2024-06-09 09:58:59 django-1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
2024-06-09 09:58:59 django-1          |     response = self.process_exception_by_middleware(e, request)
2024-06-09 09:58:59 django-1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
2024-06-09 09:58:59 django-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272700+00:00 [info] <0.254.0> Running boot step rabbit_mirror_queue_mode_nodes defined by app rabbit
2024-06-09 09:58:59 django-1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2024-06-09 09:58:59 django-1          |     return view_func(*args, **kwargs)
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272771+00:00 [info] <0.254.0> Running boot step rabbit_priority_queue defined by app rabbit
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272803+00:00 [info] <0.254.0> Priority queues enabled, real BQ is rabbit_variable_queue
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272844+00:00 [info] <0.254.0> Running boot step rabbit_queue_location_client_local defined by app rabbit
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272875+00:00 [info] <0.254.0> Running boot step rabbit_queue_location_min_masters defined by app rabbit
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272891+00:00 [info] <0.254.0> Running boot step rabbit_queue_location_random defined by app rabbit
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272906+00:00 [info] <0.254.0> Running boot step kernel_ready defined by app rabbit
2024-06-09 09:58:59 django-1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 116, in view
2024-06-09 09:58:59 django-1          |     return self.dispatch(request, *args, **kwargs)
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272913+00:00 [info] <0.254.0> Running boot step rabbit_sysmon_minder defined by app rabbit
2024-06-09 09:58:59 django-1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 495, in dispatch
2024-06-09 09:58:59 django-1          |     response = self.handle_exception(exc)
2024-06-09 09:53:40 rabbit-1          | 2024-06-09 06:53:40.272968+00:00 [info] <0.254.0> Running boot step rabbit_epmd_monitor defined by app rabbit
2024-06-09 09:58:59 django-1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 455, in handle_exception
2024-06-09 09:58:59 django-1          |     self.raise_uncaught_exception(exc)
2024-06-09 09:58:59 django-1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 492, in dispatch
2024-06-09 09:58:59 django-1          |     response = handler(request, *args, **kwargs)
2024-06-09 09:58:59 django-1          |   File "/app/src/apps/api/views/datasets.py", line 85, in create
2024-06-09 09:58:59 django-1          |     file_size = float(request.data['file_size'])
```

**Comment by Didayolo** [comment]
Maybe related to:
- #1468

> Another concerning info that is leaked is the whitelist_emails

Indeed:

- #1366

**Comment by ihsaan-ullah** [comment]
I cannot reproduce the issue you have mentioned about `file_size`. Here is what I did:

1. Using latest develop branch
2. Run `docker-compose up -d`
3. Run `docker-compose exec django ./manage.py migrate`
4. Run `docker-compose exec django ./manage.py collectstatic --noinput`
5. Access codabench using `localhost`
6. create a new user using Signup
7. Activate this user using the activation link from django container
8. Login 
9. Go to Benchmarks -> Management, upload this bundle: [iris_competition_bundle.zip](https://github.com/user-attachments/files/16281107/iris_competition_bundle.zip)

I see no error in django container

@liviust if you can reproduce the issue, please share the steps here.

**Comment by ihsaan-ullah** [comment]
# Todos:

- [ ] Fix competition printing in console
- [ ] Fix file_size error

**Comment by ihsaan-ullah** [comment]
@liviust can you reproduce this bug of `file_size`?
