### ISSUE TITLE
Custom queue creation: An error occurred

### ISSUE THREAD

**Issue by flhammer** [codalab/codabench#1558]
Hi,

I am not able to create a custom queue, see figure.

![image](https://github.com/user-attachments/assets/4381c615-6486-4d40-ab1f-0eeba91372c0)

**Comment by ihsaan-ullah** [comment]
This only happens on the production. I am unable to reproduce this locally and on test server. 
To check: django logs

**Comment by ObadaS** [comment]
I checked in the logs and found this error when someone tries to create a custom Queue.
The RabbitMQ container does not seem to generate any error in its log, this is only visible in the Django container.


```python
Making new rabbitmq user for obada
Internal Server Error: /api/queues/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/src/apps/api/views/queues.py", line 41, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/app/src/apps/api/mixins.py", line 18, in create
    return super().create(validated_data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 943, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/src/apps/queues/models.py", line 47, in save
    self.vhost = rabbit.create_queue(self.owner)
  File "/app/src/apps/queues/rabbit.py", line 63, in create_queue
    initialize_user(user, conn)
  File "/app/src/apps/queues/rabbit.py", line 44, in initialize_user
    connection.create_user(str(user.rabbitmq_username), str(user.rabbitmq_password))
  File "/usr/local/lib/python3.9/site-packages/pyrabbit2/api.py", line 949, in create_user
    return self._call(path, 'PUT', body=body,
  File "/usr/local/lib/python3.9/site-packages/pyrabbit2/api.py", line 123, in _call
    resp = self.http.do_call(path, method, body, headers, params)
  File "/usr/local/lib/python3.9/site-packages/pyrabbit2/http.py", line 110, in do_call
    raise HTTPError(content, resp.status_code, resp.text, path, body)
pyrabbit2.http.HTTPError: 502

[multiple lines of HTML code]

 (None) (users/[...]) ('{"password": "[...]", "tags": ""}')
Internal Server Error: /api/queues/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/src/apps/api/views/queues.py", line 41, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/app/src/apps/api/mixins.py", line 18, in create
    return super().create(validated_data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 943, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/src/apps/queues/models.py", line 47, in save
    self.vhost = rabbit.create_queue(self.owner)
  File "/app/src/apps/queues/rabbit.py", line 63, in create_queue
    initialize_user(user, conn)
  File "/app/src/apps/queues/rabbit.py", line 44, in initialize_user
    connection.create_user(str(user.rabbitmq_username), str(user.rabbitmq_password))
  File "/usr/local/lib/python3.9/site-packages/pyrabbit2/api.py", line 949, in create_user
    return self._call(path, 'PUT', body=body,
  File "/usr/local/lib/python3.9/site-packages/pyrabbit2/api.py", line 123, in _call
    resp = self.http.do_call(path, method, body, headers, params)
  File "/usr/local/lib/python3.9/site-packages/pyrabbit2/http.py", line 110, in do_call
    raise HTTPError(content, resp.status_code, resp.text, path, body)
pyrabbit2.http.HTTPError: 502
```
The log also shows some HTML code which I copied and opened in a browser:

![image](https://github.com/user-attachments/assets/16aff36b-e585-4ae7-9aab-71f8acaaf3e5)

[...] means the text was removed by me since it can be considered sensitive data.

**Comment by Didayolo** [comment]
```python
codabench-django-1         | Making new rabbitmq user for pavao
codabench-django-1         | Internal Server Error: /api/queues/
codabench-django-1         | Traceback (most recent call last):
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
codabench-django-1         |     response = get_response(request)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
codabench-django-1         |     response = self.process_exception_by_middleware(e, request)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
codabench-django-1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
codabench-django-1         |     return view_func(*args, **kwargs)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 116, in view
codabench-django-1         |     return self.dispatch(request, *args, **kwargs)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 495, in dispatch
codabench-django-1         |     response = self.handle_exception(exc)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 455, in handle_exception
codabench-django-1         |     self.raise_uncaught_exception(exc)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 492, in dispatch
codabench-django-1         |     response = handler(request, *args, **kwargs)
codabench-django-1         |   File "/app/src/apps/api/views/queues.py", line 41, in create
codabench-django-1         |     self.perform_create(serializer)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 26, in perform_create
codabench-django-1         |     serializer.save()
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 214, in save
codabench-django-1         |     self.instance = self.create(validated_data)
codabench-django-1         |   File "/app/src/apps/api/mixins.py", line 18, in create
codabench-django-1         |     return super().create(validated_data)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 943, in create
codabench-django-1         |     instance = ModelClass._default_manager.create(**validated_data)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
codabench-django-1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 422, in create
codabench-django-1         |     obj.save(force_insert=True, using=self.db)
codabench-django-1         |   File "/app/src/apps/queues/models.py", line 47, in save
codabench-django-1         |     self.vhost = rabbit.create_queue(self.owner)
codabench-django-1         |   File "/app/src/apps/queues/rabbit.py", line 63, in create_queue
codabench-django-1         |     initialize_user(user, conn)
codabench-django-1         |   File "/app/src/apps/queues/rabbit.py", line 44, in initialize_user
codabench-django-1         |     connection.create_user(str(user.rabbitmq_username), str(user.rabbitmq_password))
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/pyrabbit2/api.py", line 949, in create_user
codabench-django-1         |     return self._call(path, 'PUT', body=body,
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/pyrabbit2/api.py", line 123, in _call
codabench-django-1         |     resp = self.http.do_call(path, method, body, headers, params)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/pyrabbit2/http.py", line 110, in do_call
codabench-django-1         |     raise HTTPError(content, resp.status_code, resp.text, path, body)
codabench-django-1         | pyrabbit2.http.HTTPError: 502 - <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
codabench-django-1         | <html><head>
codabench-django-1         | <meta type="copyright" content="Copyright (C) 1996-2020 The Squid Software Foundation and contributors">
codabench-django-1         | <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
codabench-django-1         | <title>ERROR: The requested URL could not be retrieved</title>
codabench-django-1         | <style type="text/css"><!-- 
codabench-django-1         |  /*
codabench-django-1         |  * Copyright (C) 1996-2022 The Squid Software Foundation and contributors
codabench-django-1         |  *
codabench-django-1         |  * Squid software is distributed under GPLv2+ license and includes
codabench-django-1         |  * contributions from numerous individuals and organizations.
codabench-django-1         |  * Please see the COPYING and CONTRIBUTORS files for details.
codabench-django-1         |  */
codabench-django-1         | 
codabench-django-1         | /*
codabench-django-1         |  Stylesheet for Squid Error pages
codabench-django-1         |  Adapted from design by Free CSS Templates
codabench-django-1         |  http://www.freecsstemplates.org
codabench-django-1         |  Released for free under a Creative Commons Attribution 2.5 License
codabench-django-1         | */
codabench-django-1         | 
codabench-django-1         | /* Page basics */
codabench-django-1         | * {
codabench-django-1         | 	font-family: verdana, sans-serif;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | html body {
codabench-django-1         | 	margin: 0;
codabench-django-1         | 	padding: 0;
codabench-django-1         | 	background: #efefef;
codabench-django-1         | 	font-size: 12px;
codabench-django-1         | 	color: #1e1e1e;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* Page displayed title area */
codabench-django-1         | #titles {
codabench-django-1         | 	margin-left: 15px;
codabench-django-1         | 	padding: 10px;
codabench-django-1         | 	padding-left: 100px;
codabench-django-1         | 	background: url('/squid-internal-static/icons/SN.png') no-repeat left;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* initial title */
codabench-django-1         | #titles h1 {
codabench-django-1         | 	color: #000000;
codabench-django-1         | }
codabench-django-1         | #titles h2 {
codabench-django-1         | 	color: #000000;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* special event: FTP success page titles */
codabench-django-1         | #titles ftpsuccess {
codabench-django-1         | 	background-color:#00ff00;
codabench-django-1         | 	width:100%;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* Page displayed body content area */
codabench-django-1         | #content {
codabench-django-1         | 	padding: 10px;
codabench-django-1         | 	background: #ffffff;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* General text */
codabench-django-1         | p {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* error brief description */
codabench-django-1         | #error p {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* some data which may have caused the problem */
codabench-django-1         | #data {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* the error message received from the system or other software */
codabench-django-1         | #sysmsg {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | pre {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* special event: FTP / Gopher directory listing */
codabench-django-1         | #dirmsg {
codabench-django-1         |     font-family: courier, monospace;
codabench-django-1         |     color: black;
codabench-django-1         |     font-size: 10pt;
codabench-django-1         | }
codabench-django-1         | #dirlisting {
codabench-django-1         |     margin-left: 2%;
codabench-django-1         |     margin-right: 2%;
codabench-django-1         | }
codabench-django-1         | #dirlisting tr.entry td.icon,td.filename,td.size,td.date {
codabench-django-1         |     border-bottom: groove;
codabench-django-1         | }
codabench-django-1         | #dirlisting td.size {
codabench-django-1         |     width: 50px;
codabench-django-1         |     text-align: right;
codabench-django-1         |     padding-right: 5px;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* horizontal lines */
codabench-django-1         | hr {
codabench-django-1         | 	margin: 0;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* page displayed footer area */
codabench-django-1         | #footer {
codabench-django-1         | 	font-size: 9px;
codabench-django-1         | 	padding-left: 10px;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | 
codabench-django-1         | body
codabench-django-1         | :lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; }
codabench-django-1         | :lang(he) { direction: rtl; }
codabench-django-1         |  --></style>
codabench-django-1         | </head><body id=ERR_READ_ERROR>
codabench-django-1         | <div id="titles">
codabench-django-1         | <h1>ERROR</h1>
codabench-django-1         | <h2>The requested URL could not be retrieved</h2>
codabench-django-1         | </div>
codabench-django-1         | <hr>
codabench-django-1         | 
codabench-django-1         | <div id="content">
codabench-django-1         | <p>The following error was encountered while trying to retrieve the URL: <a href="http://rabbit:15672/api/users/26df2d3e-345e-472b-9d41-6e1ae58c4202">http://rabbit:15672/api/users/26df2d3e-345e-472b-9d41-6e1ae58c4202</a></p>
codabench-django-1         | 
codabench-django-1         | <blockquote id="error">
codabench-django-1         | <p><b>Read Error</b></p>
codabench-django-1         | </blockquote>
codabench-django-1         | 
codabench-django-1         | <p id="sysmsg">The system returned: <i>[No Error]</i></p>
codabench-django-1         | 
codabench-django-1         | <p>An error condition occurred while reading data from the network. Please retry your request.</p>
codabench-django-1         | 
codabench-django-1         | <p>Your cache administrator is <a href="mailto:webmaster?subject=CacheErrorInfo%20-%20ERR_READ_ERROR&amp;body=CacheHost%3A%20proxy-web%0D%0AErrPage%3A%20ERR_READ_ERROR%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Tue,%2006%20Aug%202024%2015%3A13%3A55%20GMT%0D%0A%0D%0AClientIP%3A%2010.152.50.23%0D%0A%0D%0AHTTP%20Request%3A%0D%0APUT%20%2Fapi%2Fusers%2F26df2d3e-345e-472b-9d41-6e1ae58c4202%20HTTP%2F1.1%0AUser-Agent%3A%20python-requests%2F2.32.3%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0AAccept%3A%20*%2F*%0D%0AConnection%3A%20keep-alive%0D%0AContent-Type%3A%20application%2Fjson%0D%0AContent-Length%3A%2064%0D%0AAuthorization%3A%20Basic%20cmFiYml0LWNvbXB2MjpyYWJiaXQ6ITIwMjE6YWM1NWJlM2E%3D%0D%0AHost%3A%20rabbit%3A15672%0D%0A%0D%0A%0D%0A">webmaster</a>.</p>
codabench-django-1         | <br>
codabench-django-1         | </div>
codabench-django-1         | 
codabench-django-1         | <hr>
codabench-django-1         | <div id="footer">
codabench-django-1         | <p>Generated Tue, 06 Aug 2024 15:13:55 GMT by proxy-web (squid/5.7)</p>
codabench-django-1         | <!-- ERR_READ_ERROR -->
codabench-django-1         | </div>
codabench-django-1         | </body></html>
codabench-django-1         |  (None) (users/26df2d3e-345e-472b-9d41-6e1ae58c4202) ('{"password": "6a7f18d6-85a0-455f-9069-9903297abd15", "tags": ""}')
codabench-django-1         | Internal Server Error: /api/queues/
codabench-django-1         | Traceback (most recent call last):
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
codabench-django-1         |     response = get_response(request)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
codabench-django-1         |     response = self.process_exception_by_middleware(e, request)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
codabench-django-1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
codabench-django-1         |     return view_func(*args, **kwargs)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 116, in view
codabench-django-1         |     return self.dispatch(request, *args, **kwargs)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 495, in dispatch
codabench-django-1         |     response = self.handle_exception(exc)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 455, in handle_exception
codabench-django-1         |     self.raise_uncaught_exception(exc)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 492, in dispatch
codabench-django-1         |     response = handler(request, *args, **kwargs)
codabench-django-1         |   File "/app/src/apps/api/views/queues.py", line 41, in create
codabench-django-1         |     self.perform_create(serializer)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 26, in perform_create
codabench-django-1         |     serializer.save()
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 214, in save
codabench-django-1         |     self.instance = self.create(validated_data)
codabench-django-1         |   File "/app/src/apps/api/mixins.py", line 18, in create
codabench-django-1         |     return super().create(validated_data)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 943, in create
codabench-django-1         |     instance = ModelClass._default_manager.create(**validated_data)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
codabench-django-1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 422, in create
codabench-django-1         |     obj.save(force_insert=True, using=self.db)
codabench-django-1         |   File "/app/src/apps/queues/models.py", line 47, in save
codabench-django-1         |     self.vhost = rabbit.create_queue(self.owner)
codabench-django-1         |   File "/app/src/apps/queues/rabbit.py", line 63, in create_queue
codabench-django-1         |     initialize_user(user, conn)
codabench-django-1         |   File "/app/src/apps/queues/rabbit.py", line 44, in initialize_user
codabench-django-1         |     connection.create_user(str(user.rabbitmq_username), str(user.rabbitmq_password))
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/pyrabbit2/api.py", line 949, in create_user
codabench-django-1         |     return self._call(path, 'PUT', body=body,
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/pyrabbit2/api.py", line 123, in _call
codabench-django-1         |     resp = self.http.do_call(path, method, body, headers, params)
codabench-django-1         |   File "/usr/local/lib/python3.9/site-packages/pyrabbit2/http.py", line 110, in do_call
codabench-django-1         |     raise HTTPError(content, resp.status_code, resp.text, path, body)
codabench-django-1         | pyrabbit2.http.HTTPError: 502 - <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
codabench-django-1         | <html><head>
codabench-django-1         | <meta type="copyright" content="Copyright (C) 1996-2020 The Squid Software Foundation and contributors">
codabench-django-1         | <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
codabench-django-1         | <title>ERROR: The requested URL could not be retrieved</title>
codabench-django-1         | <style type="text/css"><!-- 
codabench-django-1         |  /*
codabench-django-1         |  * Copyright (C) 1996-2022 The Squid Software Foundation and contributors
codabench-django-1         |  *
codabench-django-1         |  * Squid software is distributed under GPLv2+ license and includes
codabench-django-1         |  * contributions from numerous individuals and organizations.
codabench-django-1         |  * Please see the COPYING and CONTRIBUTORS files for details.
codabench-django-1         |  */
codabench-django-1         | 
codabench-django-1         | /*
codabench-django-1         |  Stylesheet for Squid Error pages
codabench-django-1         |  Adapted from design by Free CSS Templates
codabench-django-1         |  http://www.freecsstemplates.org
codabench-django-1         |  Released for free under a Creative Commons Attribution 2.5 License
codabench-django-1         | */
codabench-django-1         | 
codabench-django-1         | /* Page basics */
codabench-django-1         | * {
codabench-django-1         | 	font-family: verdana, sans-serif;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | html body {
codabench-django-1         | 	margin: 0;
codabench-django-1         | 	padding: 0;
codabench-django-1         | 	background: #efefef;
codabench-django-1         | 	font-size: 12px;
codabench-django-1         | 	color: #1e1e1e;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* Page displayed title area */
codabench-django-1         | #titles {
codabench-django-1         | 	margin-left: 15px;
codabench-django-1         | 	padding: 10px;
codabench-django-1         | 	padding-left: 100px;
codabench-django-1         | 	background: url('/squid-internal-static/icons/SN.png') no-repeat left;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* initial title */
codabench-django-1         | #titles h1 {
codabench-django-1         | 	color: #000000;
codabench-django-1         | }
codabench-django-1         | #titles h2 {
codabench-django-1         | 	color: #000000;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* special event: FTP success page titles */
codabench-django-1         | #titles ftpsuccess {
codabench-django-1         | 	background-color:#00ff00;
codabench-django-1         | 	width:100%;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* Page displayed body content area */
codabench-django-1         | #content {
codabench-django-1         | 	padding: 10px;
codabench-django-1         | 	background: #ffffff;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* General text */
codabench-django-1         | p {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* error brief description */
codabench-django-1         | #error p {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* some data which may have caused the problem */
codabench-django-1         | #data {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* the error message received from the system or other software */
codabench-django-1         | #sysmsg {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | pre {
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* special event: FTP / Gopher directory listing */
codabench-django-1         | #dirmsg {
codabench-django-1         |     font-family: courier, monospace;
codabench-django-1         |     color: black;
codabench-django-1         |     font-size: 10pt;
codabench-django-1         | }
codabench-django-1         | #dirlisting {
codabench-django-1         |     margin-left: 2%;
codabench-django-1         |     margin-right: 2%;
codabench-django-1         | }
codabench-django-1         | #dirlisting tr.entry td.icon,td.filename,td.size,td.date {
codabench-django-1         |     border-bottom: groove;
codabench-django-1         | }
codabench-django-1         | #dirlisting td.size {
codabench-django-1         |     width: 50px;
codabench-django-1         |     text-align: right;
codabench-django-1         |     padding-right: 5px;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* horizontal lines */
codabench-django-1         | hr {
codabench-django-1         | 	margin: 0;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | /* page displayed footer area */
codabench-django-1         | #footer {
codabench-django-1         | 	font-size: 9px;
codabench-django-1         | 	padding-left: 10px;
codabench-django-1         | }
codabench-django-1         | 
codabench-django-1         | 
codabench-django-1         | body
codabench-django-1         | :lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; }
codabench-django-1         | :lang(he) { direction: rtl; }
codabench-django-1         |  --></style>
codabench-django-1         | </head><body id=ERR_READ_ERROR>
codabench-django-1         | <div id="titles">
codabench-django-1         | <h1>ERROR</h1>
codabench-django-1         | <h2>The requested URL could not be retrieved</h2>
codabench-django-1         | </div>
codabench-django-1         | <hr>
codabench-django-1         | 
codabench-django-1         | <div id="content">
codabench-django-1         | <p>The following error was encountered while trying to retrieve the URL: <a href="http://rabbit:15672/api/users/26df2d3e-345e-472b-9d41-6e1ae58c4202">http://rabbit:15672/api/users/26df2d3e-345e-472b-9d41-6e1ae58c4202</a></p>
codabench-django-1         | 
codabench-django-1         | <blockquote id="error">
codabench-django-1         | <p><b>Read Error</b></p>
codabench-django-1         | </blockquote>
codabench-django-1         | 
codabench-django-1         | <p id="sysmsg">The system returned: <i>[No Error]</i></p>
codabench-django-1         | 
codabench-django-1         | <p>An error condition occurred while reading data from the network. Please retry your request.</p>
codabench-django-1         | 
codabench-django-1         | <p>Your cache administrator is <a href="mailto:webmaster?subject=CacheErrorInfo%20-%20ERR_READ_ERROR&amp;body=CacheHost%3A%20proxy-web%0D%0AErrPage%3A%20ERR_READ_ERROR%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Tue,%2006%20Aug%202024%2015%3A13%3A55%20GMT%0D%0A%0D%0AClientIP%3A%2010.152.50.23%0D%0A%0D%0AHTTP%20Request%3A%0D%0APUT%20%2Fapi%2Fusers%2F26df2d3e-345e-472b-9d41-6e1ae58c4202%20HTTP%2F1.1%0AUser-Agent%3A%20python-requests%2F2.32.3%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0AAccept%3A%20*%2F*%0D%0AConnection%3A%20keep-alive%0D%0AContent-Type%3A%20application%2Fjson%0D%0AContent-Length%3A%2064%0D%0AAuthorization%3A%20Basic%20cmFiYml0LWNvbXB2MjpyYWJiaXQ6ITIwMjE6YWM1NWJlM2E%3D%0D%0AHost%3A%20rabbit%3A15672%0D%0A%0D%0A%0D%0A">webmaster</a>.</p>
codabench-django-1         | <br>
codabench-django-1         | </div>
codabench-django-1         | 
codabench-django-1         | <hr>
codabench-django-1         | <div id="footer">
codabench-django-1         | <p>Generated Tue, 06 Aug 2024 15:13:55 GMT by proxy-web (squid/5.7)</p>
codabench-django-1         | <!-- ERR_READ_ERROR -->
codabench-django-1         | </div>
codabench-django-1         | </body></html>
codabench-django-1         |  (None) (users/26df2<hidden>8c4202) ('{"password": "6a7f18d<hidden>97abd15", "tags": ""}')
```

**Comment by Didayolo** [comment]
I confirm it is working locally and on the test server. We encounter the problem only on production.

**Comment by Didayolo** [comment]
The infrastructure is currently experiencing internet connection issues, it could be related.

**Comment by Didayolo** [comment]
> The infrastructure is currently experiencing internet connection issues, it could be related.

The infrastructure is still unstable today. Thank you for your patience.

**Comment by Steveolas** [comment]
I am still getting the same issue. Are there any updates?

**Comment by Didayolo** [comment]
Unfortunately the issue is still present. We have a meeting today with the team to work on it.

**Comment by Steveolas** [comment]
Great! thanks for the update

**Comment by Didayolo** [comment]
We may have identified the problem. The staff from the network service at fault here is not available until Monday. We're waiting their return to solve this as soon as possible.

**Comment by ObadaS** [comment]
@flhammer @Steveolas Hello, the problem has been fixed.
