### ISSUE TITLE
Unable to Connect Compute worker: Rabbit MQ Problem

### ISSUE THREAD

**Issue by chansmi** [codalab/codabench#1599]
I set up a new VM, I followed the instructions on a the wiki. I did this successfully for creating one compute worker, but when I went to create a second I got an error. 

I confirmed I have the right code and am logged into docker on the vm. 

I also tried to stop and remove the worker but it happened when I tried to create it again.
```

/usr/local/lib/python3.9/site-packages/celery/platforms.py:800: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(

 -------------- compute-worker@c1e56da50b9e v4.4.0 (cliffs)
--- ***** -----
-- ******* ---- Linux-6.1.0-25-cloud-amd64-x86_64-with-glibc2.36 2024-09-27 15:44:40
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7f6b720bd5e0
- ** ---------- .> transport:   amqp://c585dc19-8656-46a7-9Xfcf-b20d38d75488:**@www.codabench.org:5672/8924a160-e8d9-480c-9d5c-7619ec69428c
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> compute-worker   exchange=compute-worker(direct) key=compute-worker


[tasks]
  . compute_worker_run

[2024-09-27 15:44:41,340: CRITICAL/MainProcess] Unrecoverable error: AccessRefused(403, 'ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.', (0, 0), '')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/connection.py", line 23, in start
    c.connection = c.connect()
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 405, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 411, in connection_for_read
    return self.ensure_connected(
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 434, in ensure_connected
    conn = conn.ensure_connection(
  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 389, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 441, in _ensure_connection
    return retry_over_time(
  File "/usr/local/lib/python3.9/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 874, in _connection_factory
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 809, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.9/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/amqp/connection.py", line 320, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/usr/local/lib/python3.9/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.9/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.9/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.9/site-packages/amqp/connection.py", line 520, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/usr/local/lib/python3.9/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.9/site-packages/amqp/connection.py", line 650, in _on_close
    raise error_for_code(reply_code, reply_text,
amqp.exceptions.AccessRefused: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
chansmi@instance-20240925-20240927-151454:~$
```

**Comment by ObadaS** [comment]
Hello, 
Are you trying to create multiple workers in the same VM or in different VMs ?

**Comment by chansmi** [comment]
Different VMS, same access link though from the queue management

**Comment by ObadaS** [comment]
That's pretty weird.
Have you tried creating a new Broker URL and using it on new workers to see if it works ?

I am assuming that those VMs are in the same network and the same overall environment ?
