### ISSUE TITLE
BUG: Failure updating submission data

### ISSUE THREAD

**Issue by EugenioTL** [codalab/codabench#1656]
Dear codabench moderators,

we are the authors of the ongoing competition with ID 4430 and title Artificial Neural Networks and Deep Learning [2024-2025] - Homework 1.
After a reset of the leaderboard we are facing the following error for each submission, even the ones that were working properly:

```
an2dl-worker1  | [2024-11-11 14:16:05,971: INFO/MainProcess] Received task: compute_worker_run[8a01aa71-2464-494c-922a-e0500e19aca6]
an2dl-worker1  | [2024-11-11 14:16:05,974: INFO/ForkPoolWorker-1] Received run arguments: {'user_pk': 10859, 'submissions_api_url': 'https://www.codabench.org/api', 'secret': '313bccf8-f263-44f0-8a8a-b22376853b20', 'docker_image': 'aarchetti/codabench:1.1', 'execution_time_limit': 600, 'id': 138732, 'is_scoring': False, 'prediction_result': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/prediction_result/2024-11-11-1731334475/528ea0ee23d6/prediction_result.zip?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=F8Nm2YNUnPQpKsv7Ls%2B3y%2BYrxDU%3D&content-type=application%2Fzip&Expires=1731420875', 'ingestion_program': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/dataset/2024-11-06-1730887445/96b193dc3816/ingestion_program.zip?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=81eU3n9wIrAPhIWXDi5GYiDeBXU%3D&Expires=1731420875', 'input_data': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/dataset/2024-11-06-1730887446/19e7c17b43aa/test_data_dev_phase.zip?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=HGym9qGFWtVSWMY3eJzwSURB5io%3D&Expires=1731420875', 'ingestion_only_during_scoring': False, 'program_data': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/dataset/2024-11-11-1731334473/a99a8255c9b9/submission_241104_174049.zip?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=RLK3uwskQikLQ4xGXzhc2GU6E2g%3D&Expires=1731420875', 'prediction_stdout': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/submission_details/2024-11-11-1731334475/fa710c3be175/prediction_stdout.txt?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=3TKEY2TyniMXc2eI6KiSPHMPBNo%3D&content-type=application%2Fzip&Expires=1731420875', 'prediction_stderr': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/submission_details/2024-11-11-1731334475/fd3b31a2635a/prediction_stderr.txt?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=C1ByOMM7UrZ%2BpGR0sO5BKGdzvz4%3D&content-type=application%2Fzip&Expires=1731420876', 'prediction_ingestion_stdout': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/submission_details/2024-11-11-1731334476/0c4b2d541bef/prediction_ingestion_stdout.txt?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=zBN8FwIEc2k4PI%2FhzgUro0hUkQE%3D&content-type=application%2Fzip&Expires=1731420876', 'prediction_ingestion_stderr': 'https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-private/submission_details/2024-11-11-1731334476/310b79f4ad90/prediction_ingestion_stderr.txt?AWSAccessKeyId=EASNOMJFX9QFW4QIY4SL&Signature=iBVf2ZgJwM3LyZmi0fdqzeHoPYQ%3D&content-type=application%2Fzip&Expires=1731420876'}
an2dl-worker1  | [2024-11-11 14:16:05,977: INFO/ForkPoolWorker-1] Updating submission @ https://www.codabench.org/api/submissions/138732/ with data = {'status': 'Preparing', 'status_details': None, 'secret': '313bccf8-f263-44f0-8a8a-b22376853b20'}
an2dl-worker1  | [2024-11-11 14:16:06,191: INFO/ForkPoolWorker-1] Submission patch failed with status = 500, and response =
an2dl-worker1  | b'<h1>Server Error (500)</h1>'
an2dl-worker1  | [2024-11-11 14:16:06,191: INFO/ForkPoolWorker-1] Updating submission @ https://www.codabench.org/api/submissions/138732/ with data = {'status': 'Failed', 'status_details': 'Failure updating submission data.', 'secret': '313bccf8-f263-44f0-8a8a-b22376853b20'}
an2dl-worker1  | [2024-11-11 14:16:06,334: INFO/ForkPoolWorker-1] Submission patch failed with status = 500, and response =
an2dl-worker1  | b'<h1>Server Error (500)</h1>'
an2dl-worker1  | [2024-11-11 14:16:06,334: INFO/ForkPoolWorker-1] Destroying submission temp dir: /codabench/tmp0_rzb1ms
an2dl-worker1  | [2024-11-11 14:16:06,337: ERROR/ForkPoolWorker-1] Task compute_worker_run[8a01aa71-2464-494c-922a-e0500e19aca6] raised unexpected: SubmissionException('Failure updating submission data.')
an2dl-worker1  | Traceback (most recent call last):
an2dl-worker1  |   File "/compute_worker.py", line 112, in run_wrapper
an2dl-worker1  |     run.prepare()
an2dl-worker1  |   File "/compute_worker.py", line 765, in prepare
an2dl-worker1  |     self._update_status(STATUS_PREPARING)
an2dl-worker1  |   File "/compute_worker.py", line 356, in _update_status
an2dl-worker1  |     self._update_submission(data)
an2dl-worker1  |   File "/compute_worker.py", line 339, in _update_submission
an2dl-worker1  |     raise SubmissionException("Failure updating submission data.")
an2dl-worker1  | compute_worker.SubmissionException: Failure updating submission data.
an2dl-worker1  |
an2dl-worker1  | During handling of the above exception, another exception occurred:
an2dl-worker1  |
an2dl-worker1  | Traceback (most recent call last):
an2dl-worker1  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task
an2dl-worker1  |     R = retval = fun(*args, **kwargs)
an2dl-worker1  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 650, in __protected_call__
an2dl-worker1  |     return self.run(*args, **kwargs)
an2dl-worker1  |   File "/compute_worker.py", line 120, in run_wrapper
an2dl-worker1  |     run._update_status(STATUS_FAILED, str(e))
an2dl-worker1  |   File "/compute_worker.py", line 356, in _update_status
an2dl-worker1  |     self._update_submission(data)
an2dl-worker1  |   File "/compute_worker.py", line 339, in _update_submission
an2dl-worker1  |     raise SubmissionException("Failure updating submission data.")
an2dl-worker1  | compute_worker.SubmissionException: Failure updating submission data.
```

We rally need to fix it and to make thing working as soon as possible. Given that we have seen it is something already happened and fixed from your side, we ask your effort.
Thank you very much.

**Comment by ObadaS** [comment]
Hello, do you still have this problem ? I fixed it yesterday, and it does not seem to be currently bugged.

**Comment by archettialberto** [comment]
Hi @ObadaS, thanks for the support! I confirm that the system is running for competition 4430, we are receiving and processing submissions correctly.

**Comment by ObadaS** [comment]
That's great ! I will close the issue then since it's resolved for now.
