### ISSUE TITLE
Unable to save new tasks

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#1686]
# Description

Issue related to saving new tasks in Codabench. The issue is explained step-by-step in this document: 
[https://docs.google.com/document/d/1-InYnhHznnU0nqGfxfmHKYfSTsLX_klB4V32Uf08SNQ/edit?usp=sharing](https://docs.google.com/document/d/1-InYnhHznnU0nqGfxfmHKYfSTsLX_klB4V32Uf08SNQ/edit?usp=sharing)

# Error logs

```python
django-1  | Internal Server Error: /api/competitions/3863/
django-1  | Traceback (most recent call last):
django-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
django-1  |     response = get_response(request)
django-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
django-1  |     response = self.process_exception_by_middleware(e, request)
django-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
django-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django-1  |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django-1  |     return view_func(*args, **kwargs)
django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 116, in view
django-1  |     return self.dispatch(request, *args, **kwargs)
django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 495, in dispatch
django-1  |     response = self.handle_exception(exc)
django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 455, in handle_exception
django-1  |     self.raise_uncaught_exception(exc)
django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 492, in dispatch
django-1  |     response = handler(request, *args, **kwargs)
django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 84, in partial_update
django-1  |     return self.update(request, *args, **kwargs)
django-1  |   File "/app/src/apps/api/views/competitions.py", line 311, in update
django-1  |     self.perform_update(serializer)
django-1  |   File "/app/src/apps/api/views/competitions.py", line 590, in perform_update
django-1  |     self.run_new_task_submissions(instance.phases.get(pk=phase_id), new_tasks)
django-1  |   File "/app/src/apps/api/views/competitions.py", line 563, in run_new_task_submissions
django-1  |     leaderboard=submission.children.first().leaderboard,
django-1  | AttributeError: 'NoneType' object has no attribute 'leaderboard'
```

**Comment by shmuhammadd** [comment]
@Didayolo jjust checking in on this!

We are about to start our evaluation phase and are still facing this issue.

We tried creating a new Codabench from scratch with all the tasks we wanted, and it worked. However, we don’t want to migrate to a new Codabench as we already have many participants (421, the largest on Codabench to date).

**Comment by Didayolo** [comment]
@ihsaan-ullah May have a clue about this problem. Please keep us updated.

**Comment by ihsaan-ullah** [comment]
When you update a competition by adding a new task to a phase, the following happens:
- we fetch all submissions that are parent submissions
- we loop over all these submissions and we find missing tasks (missing task = all_tasks_of_this_phase - submission.children.tasks).
- we then create a new submission which is a child submission with this new task or missing task
- Problem occurs in the leaderboard assigning
```python
leaderboard=submission.children.first().leaderboard
```
Error says `AttributeError: 'NoneType' object has no attribute 'leaderboard'`. children.first is None. I am checking why it is None

**Comment by ihsaan-ullah** [comment]
I tired to debug this problem using the following steps:

1. Uploaded a new competition 
2. Added 2 tasks to the final phase (Dev Task and Final Task)
3. Ran 2 submissions (one on dev task only, second on the 2 tasks)
4. Added a new task to the phase and everything went well without any problem

Do you know how to reproduce this issue?

**Comment by Didayolo** [comment]
Unfortunately we are still not understanding this bug. Especially as we can't reproduce it, it is just stuck to the first version of the challenge.

**Comment by Didayolo** [comment]
I close this issue as it is too specific and staling.
