### ISSUE TITLE
Submission doesn't appear after processing

### ISSUE THREAD

**Issue by dtuantran** [codalab/codabench#682]
I success to upload a submission. But after processing it, the page doesn't show the submission, same as Leader board ("results" tab)

![image](https://user-images.githubusercontent.com/7440668/156212493-8784bfde-1f8c-4a5b-bad3-c5f7cb119df3.png)

```
django_1          | Internal Server Error: /api/phases/42/get_leaderboard/
django_1          | Traceback (most recent call last):
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1          |     response = get_response(request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
django_1          |     response = self.process_exception_by_middleware(e, request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
django_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django_1          |     return view_func(*args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 116, in view
django_1          |     return self.dispatch(request, *args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 495, in dispatch
django_1          |     response = self.handle_exception(exc)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 455, in handle_exception
django_1          |     self.raise_uncaught_exception(exc)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 492, in dispatch
django_1          |     response = handler(request, *args, **kwargs)
django_1          |   File "/app/src/apps/api/views/competitions.py", line 462, in get_leaderboard
django_1          |     query = LeaderboardPhaseSerializer(phase).data
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 563, in data
django_1          |     ret = super(Serializer, self).data
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 262, in data
django_1          |     self._data = self.to_representation(self.instance)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 530, in to_representation
django_1          |     ret[field.field_name] = field.to_representation(attribute)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/fields.py", line 1893, in to_representation
django_1          |     return method(value)
django_1          |   File "/app/src/apps/api/serializers/leaderboards.py", line 148, in get_submissions
django_1          |     primary_col = instance.leaderboard.columns.get(index=instance.leaderboard.primary_index)
django_1          | AttributeError: 'NoneType' object has no attribute 'columns'
django_1          | Internal Server Error: /api/phases/42/get_leaderboard/
django_1          | Traceback (most recent call last):
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1          |     response = get_response(request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
django_1          |     response = self.process_exception_by_middleware(e, request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
django_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django_1          |     return view_func(*args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 116, in view
django_1          |     return self.dispatch(request, *args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 495, in dispatch
django_1          |     response = self.handle_exception(exc)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 455, in handle_exception
django_1          |     self.raise_uncaught_exception(exc)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 492, in dispatch
django_1          |     response = handler(request, *args, **kwargs)
django_1          |   File "/app/src/apps/api/views/competitions.py", line 462, in get_leaderboard
django_1          |     query = LeaderboardPhaseSerializer(phase).data
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 563, in data
django_1          |     ret = super(Serializer, self).data
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 262, in data
django_1          |     self._data = self.to_representation(self.instance)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 530, in to_representation
django_1          |     ret[field.field_name] = field.to_representation(attribute)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/fields.py", line 1893, in to_representation
django_1          |     return method(value)
django_1          |   File "/app/src/apps/api/serializers/leaderboards.py", line 148, in get_submissions
django_1          |     primary_col = instance.leaderboard.columns.get(index=instance.leaderboard.primary_index)
django_1          | AttributeError: 'NoneType' object has no attribute 'columns'
django_1          | Not Found: /forums/undefined/
django_1          | Not Found: /forums/undefined/
django_1          | Not Found: /favicon.ico
django_1          | Not Found: /favicon.ico
django_1          | Not Found: /competitions/207/
django_1          | Not Found: /competitions/207/
django_1          | Not Found: /competitions/207/
django_1          | Not Found: /competitions/207/
```

**Comment by Didayolo** [comment]
@dtuantran 

On my side the submission does work neither.

The submissions just remain in "running" state:

![submission_stuck](https://user-images.githubusercontent.com/11784999/159338602-18930325-5490-49c8-8b84-1e9b0780f0e1.png)

Do we have running workers linked to CodaBench right now?

**Comment by xhlulu** [comment]
FYI I'm following the tutorial here: https://github.com/codalab/codabench/wiki/Getting-started-with-Codabench

And running into this exact error. Also it seems I'm unable to submit to other competition, like this one: https://www.codabench.org/competitions/8/#/results-tab

**Comment by Didayolo** [comment]
I just realized I haven't look into the compute worker's log. When trying an a local deployment, here is what I got:

```python
[2022-07-06 12:29:27,747: INFO/MainProcess] Received task: compute_worker_run[3118fdf6-7891-41cf-9528-6e2fa82f4917]  
[2022-07-06 12:29:27,748: INFO/ForkPoolWorker-1] Received run arguments: {'user_pk': 14, 'submissions_api_url': 'http://example.com/api', 'secret': '3d837b0c-793e-47fd-8b69-2e8373b596d9', 'docker_image': 'codalab/codalab-legacy:py37', 'execution_time_limit': 500, 'id': 84, 'is_scoring': False, 'prediction_result': 'http://minio:9000/private/prediction_result/2022-07-06-1657110567/807768691c07/prediction_result.zip?AWSAccessKeyId=testkey&Signature=rTcmeoyGE9NGGbElSkd8P8%2BCmfE%3D&content-type=application%2Fzip&Expires=1657196967', 'ingestion_program': 'http://minio:9000/private/dataset/2022-07-06-1657110541/3a9d3f5ac40b/ingestion_program.zip?AWSAccessKeyId=testkey&Signature=FwmMdx8MTDWzg9KPBdpxn3ouZag%3D&Expires=1657196967', 'input_data': 'http://minio:9000/private/dataset/2022-07-06-1657110543/13a1a2dfc812/input_data_1_2.zip?AWSAccessKeyId=testkey&Signature=JVIUMCuZOvfWyrJZH36nkrg73wI%3D&Expires=1657196967', 'ingestion_only_during_scoring': False, 'program_data': 'http://minio:9000/private/dataset/2022-07-06-1657110566/13debd6edbc9/sample_result_submission.zip?AWSAccessKeyId=testkey&Signature=VXaJt8NgBHbqksVzJQq%2FA1PChr0%3D&Expires=1657196967', 'prediction_stdout': 'http://minio:9000/private/submission_details/2022-07-06-1657110567/ed84fc1cd840/prediction_stdout.txt?AWSAccessKeyId=testkey&Signature=wFNEZ4e0lnd6X66jHq6zGs2Ou3w%3D&content-type=application%2Fzip&Expires=1657196967', 'prediction_stderr': 'http://minio:9000/private/submission_details/2022-07-06-1657110567/1b242497ba2a/prediction_stderr.txt?AWSAccessKeyId=testkey&Signature=M1SqK7DHQwxMIyN4Sznee746as8%3D&content-type=application%2Fzip&Expires=1657196967', 'prediction_ingestion_stdout': 'http://minio:9000/private/submission_details/2022-07-06-1657110567/8d6aa7414417/prediction_ingestion_stdout.txt?AWSAccessKeyId=testkey&Signature=9aU3WT6TBZdynjVQd3B0WvJZJRE%3D&content-type=application%2Fzip&Expires=1657196967', 'prediction_ingestion_stderr': 'http://minio:9000/private/submission_details/2022-07-06-1657110567/cda0a7077eeb/prediction_ingestion_stderr.txt?AWSAccessKeyId=testkey&Signature=lQxP7UmDaSquga5EVddKrcbspN4%3D&content-type=application%2Fzip&Expires=1657196967'}
[2022-07-06 12:29:27,749: INFO/ForkPoolWorker-1] Updating submission @ http://example.com/api/submissions/84/ with data = {'status': 'Preparing', 'status_details': None, 'secret': '3d837b0c-793e-47fd-8b69-2e8373b596d9'}
[2022-07-06 12:29:28,051: INFO/ForkPoolWorker-1] Submission patch failed with status = 404, and response = 
b'<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset="utf-8" />\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <style type="text/css">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.</p>\n    <p><a href="https://www.iana.org/domains/example">More information...</a></p>\n</div>\n</body>\n</html>\n'
[2022-07-06 12:29:28,052: INFO/ForkPoolWorker-1] Updating submission @ http://example.com/api/submissions/84/ with data = {'status': 'Failed', 'status_details': 'Failure updating submission data.', 'secret': '3d837b0c-793e-47fd-8b69-2e8373b596d9'}
[2022-07-06 12:29:28,189: INFO/ForkPoolWorker-1] Submission patch failed with status = 404, and response = 
b'<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset="utf-8" />\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <style type="text/css">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.</p>\n    <p><a href="https://www.iana.org/domains/example">More information...</a></p>\n</div>\n</body>\n</html>\n'
[2022-07-06 12:29:28,190: INFO/ForkPoolWorker-1] CODALAB_IGNORE_CLEANUP_STEP mode enabled, ignoring clean up of: /codabench/tmptod70azt
[2022-07-06 12:29:28,245: ERROR/ForkPoolWorker-1] Task compute_worker_run[3118fdf6-7891-41cf-9528-6e2fa82f4917] raised unexpected: SubmissionException('Failure updating submission data.')
Traceback (most recent call last):
  File "/app/compute_worker.py", line 83, in run_wrapper
    run.prepare()
  File "/app/compute_worker.py", line 615, in prepare
    self._update_status(STATUS_PREPARING)
  File "/app/compute_worker.py", line 315, in _update_status
    self._update_submission(data)
  File "/app/compute_worker.py", line 299, in _update_submission
    raise SubmissionException("Failure updating submission data.")
compute_worker.SubmissionException: Failure updating submission data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/compute_worker.py", line 89, in run_wrapper
    run._update_status(STATUS_FAILED, str(e))
  File "/app/compute_worker.py", line 315, in _update_status
    self._update_submission(data)
  File "/app/compute_worker.py", line 299, in _update_submission
    raise SubmissionException("Failure updating submission data.")
compute_worker.SubmissionException: Failure updating submission data.

```

**Comment by Didayolo** [comment]
I think this issue is the problem with Firefox. I merge it.
