### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#759]
Some accounts are experiencing the impossibility to be logged in.

Note that this account worked in the past, I have signed out in order to test and indeed it does not work.

<img width="464" alt="Capture d’écran 2023-01-23 à 18 52 09" src="https://user-images.githubusercontent.com/11784999/214113100-2d038204-7634-4115-9dd9-4af5603f98aa.png">

Also, the sentence "Note that both fields **may be** case sensitive" is unclear. If username is case sensitive, then we should write "Note that both fields **are** case sensitive".

**Comment by Didayolo** [comment]
It's working again after:

```
docker-compose down
docker-compose up -d
```

We still don't know what caused the issue.

**Comment by Didayolo** [comment]
The problem seems to be related to confirmation email?

**Comment by dtuantran** [comment]
We found this error in django :

```
django_1          | Internal Server Error: /accounts/signup
django_1          | Traceback (most recent call last):
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1          |     response = get_response(request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
django_1          |     response = self.process_exception_by_middleware(e, request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
django_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1          |   File "/app/src/apps/profiles/views.py", line 120, in sign_up
django_1          |     activateEmail(request, user, form.cleaned_data.get('email'))
django_1          |   File "/app/src/apps/profiles/views.py", line 98, in activateEmail
django_1          |     if email.send():
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/message.py", line 306, in send
django_1          |     return self.get_connection(fail_silently).send_messages([self])
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
django_1          |     new_conn_created = self.open()
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open
django_1          |     self.connection = self.connection_class(self.host, self.port, **connection_params)
django_1          |   File "/usr/local/lib/python3.8/smtplib.py", line 253, in __init__
django_1          |     (code, msg) = self.connect(host, port)
django_1          |   File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
django_1          |     self.sock = self._get_socket(host, port, self.timeout)
django_1          |   File "/usr/local/lib/python3.8/smtplib.py", line 308, in _get_socket
django_1          |     return socket.create_connection((host, port), timeout,
django_1          |   File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
django_1          |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
django_1          |   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
django_1          |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
django_1          | socket.gaierror: [Errno -3] Temporary failure in name resolution

```

**Comment by Didayolo** [comment]
Related issue: #773

**Comment by Didayolo** [comment]
Account deletion if bug??

https://github.com/codalab/codabench/blob/4a6ca5c95adab97933562ae7a3d552ff9350e43e/src/apps/profiles/views.py#L82

**Comment by Didayolo** [comment]
If you have problem with signup/login please report here:
- The username
- The email address
- The password (if possible)
- The symptoms (red message, no email received, etc.)
