### ISSUE TITLE
Concerning Django logs

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#985]
In the production server, we have this Django logs, repeating every ~5 minutes:

```python
django_1          | RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
django_1          | [2023-06-23 13:08:02 +0000] [14] [INFO] ('172.19.0.11', 43088) - "WebSocket /submission_output/" 403
django_1          | [2023-06-23 13:08:02 +0000] [14] [ERROR] Exception in ASGI application
django_1          | Traceback (most recent call last):
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 157, in run_asgi
django_1          |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
django_1          |     return await self.app(scope, receive, send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
django_1          |     await instance(receive, send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/sessions.py", line 183, in __call__
django_1          |     return await self.inner(receive, self.send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/middleware.py", line 41, in coroutine_call
django_1          |     await inner_instance(receive, send)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 58, in __call__
django_1          |     await await_many_dispatch(
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
django_1          |     await dispatch(result)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 73, in dispatch
django_1          |     await handler(message)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
django_1          |     await self.disconnect(message["code"])
django_1          |   File "/app/src/apps/competitions/consumers.py", line 65, in disconnect
django_1          |     await self.close()
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/generic/websocket.py", line 226, in close
django_1          |     await super().send({"type": "websocket.close"})
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/consumer.py", line 81, in send
django_1          |     await self.base_send(message)
django_1          |   File "/usr/local/lib/python3.8/site-packages/channels/sessions.py", line 236, in send
django_1          |     return await self.real_send(message)
django_1          |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 234, in asgi_send
django_1          |     raise RuntimeError(msg % message_type)
```

**Comment by Didayolo** [comment]
@dtuantran Any thoughts on this?
