### ISSUE TITLE
Phase Update Task Status 500

### ISSUE THREAD

**Issue by spencrr** [codalab/codabench#999]
When updating the tasks for our [competition](https://www.codabench.org/competitions/984), I get 
<img width="1273" alt="Screenshot 2023-06-30 at 15 59 56" src="https://github.com/codalab/codabench/assets/23708360/2f730a07-32ea-46bd-9005-245339e31134">
Please assist this issue as we are working to restore our live competition.

cc:
@spencrr
@nick11roberts

**Comment by spencrr** [comment]
Additional details:
- Tried Chrome, Safari
- Tried different task names
- Tried adding one task at a time

**Comment by Didayolo** [comment]
Hi Spencer,

What are you updating exactly? You add a new task in the phase and remove the old one?

**Comment by ihsaan-ullah** [comment]
@spencrr 

Can you reproduce the error again? I tried but cannot reproduce.

Can you verify if it gives error in all of these

1. Remove single task and save
2. Remove multiple tasks and save
3. Add signle task and save
4. Add multiple tasks and save
4. Remove single task and add single task and save
5. Remove multiple tasks and add multiple tasks and save

**Comment by spencrr** [comment]
Hello IIhsan,

All of the following are resulting with HTTP 500s.

1. 
![image](https://github.com/codalab/codabench/assets/23708360/ba793832-10e8-4609-a3d0-a70d20892d1f)
2. I do not believe I can remove all tasks (there are only 2 for https://www.codabench.org/competitions/984/)
3. 
<img width="1064" alt="image" src="https://github.com/codalab/codabench/assets/23708360/1a715160-5215-4edb-a36f-154794c510d6">
4. Same result as (3)
5.
<img width="1212" alt="image" src="https://github.com/codalab/codabench/assets/23708360/73dbd203-b4f8-4ce9-bc13-b0eaa4b985d9">
6. This was the first thing I tried as well: 
<img width="941" alt="image" src="https://github.com/codalab/codabench/assets/23708360/36a4ce15-61da-4c77-b027-3bebb1891b53">

**Comment by Didayolo** [comment]
I can reproduce the error.

In the platform logs, I can see that some submissions can't be retrieved.

Also, when clicking on the "edit" button of the competition, there is an error message that appears and disappears very quickling stating something like "Error in retrieving submissions".

Logs:

```python
site_worker_1     | Traceback (most recent call last):
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
site_worker_1     |     R = retval = fun(*args, **kwargs)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
site_worker_1     |     return self.run(*args, **kwargs)
site_worker_1     |   File "/app/src/apps/competitions/tasks.py", line 278, in _run_submission
site_worker_1     |     submission = qs.get(pk=submission_pk)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
site_worker_1     |     raise self.model.DoesNotExist(
site_worker_1     | competitions.models.Submission.DoesNotExist: Submission matching query does not exist.
django_1          | Internal Server Error: /api/competitions/984/
django_1          | Traceback (most recent call last):
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1          |     response = get_response(request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
django_1          |     response = self.process_exception_by_middleware(e, request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
django_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django_1          |     return view_func(*args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 116, in view
django_1          |     return self.dispatch(request, *args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 495, in dispatch
django_1          |     response = self.handle_exception(exc)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 455, in handle_exception
django_1          |     self.raise_uncaught_exception(exc)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 492, in dispatch
django_1          |     response = handler(request, *args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 84, in partial_update
django_1          |     return self.update(request, *args, **kwargs)
django_1          |   File "/app/src/apps/api/views/competitions.py", line 233, in update
django_1          |     self.perform_update(serializer)
caddy_1           | 176.136.238.116 - - [06/Jul/2023:10:49:59 +0000] "PATCH /api/competitions/984/ HTTP/2.0" 500 51
django_1          |   File "/app/src/apps/api/views/competitions.py", line 492, in perform_update
django_1          |     self.run_new_task_submissions(instance.phases.get(pk=phase_id), new_tasks)
django_1          |   File "/app/src/apps/api/views/competitions.py", line 466, in run_new_task_submissions
django_1          |     leaderboard=submission.children.first().leaderboard,
django_1          | AttributeError: 'NoneType' object has no attribute 'leaderboard'
django_1          | Internal Server Error: /api/competitions/984/
django_1          | Traceback (most recent call last):
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1          |     response = get_response(request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
django_1          |     response = self.process_exception_by_middleware(e, request)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
django_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django_1          |     return view_func(*args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 116, in view
django_1          |     return self.dispatch(request, *args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 495, in dispatch
django_1          |     response = self.handle_exception(exc)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 455, in handle_exception
django_1          |     self.raise_uncaught_exception(exc)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 492, in dispatch
django_1          |     response = handler(request, *args, **kwargs)
django_1          |   File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 84, in partial_update
django_1          |     return self.update(request, *args, **kwargs)
django_1          |   File "/app/src/apps/api/views/competitions.py", line 233, in update
django_1          |     self.perform_update(serializer)
django_1          |   File "/app/src/apps/api/views/competitions.py", line 492, in perform_update
django_1          |     self.run_new_task_submissions(instance.phases.get(pk=phase_id), new_tasks)
django_1          |   File "/app/src/apps/api/views/competitions.py", line 466, in run_new_task_submissions
django_1          |     leaderboard=submission.children.first().leaderboard,
django_1          | AttributeError: 'NoneType' object has no attribute 'leaderboard'
site_worker_1     | [2023-07-06 10:49:59,512: INFO/MainProcess] Received task: competitions.tasks._run_submission[af7310ba-4334-42f7-a47f-6da017d0c373]  
site_worker_1     | [2023-07-06 10:49:59,516: INFO/MainProcess] Received task: competitions.tasks._run_submission[4b083c13-8609-4859-b593-599d1a5644c6]  
site_worker_1     | [2023-07-06 10:49:59,528: ERROR/ForkPoolWorker-3] Task competitions.tasks._run_submission[09e1c465-cb2f-4c09-aa1a-ed5645f47a5a] raised unexpected: DoesNotExist('Submission matching query does not exist.')
site_worker_1     | Traceback (most recent call last):
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
site_worker_1     |     R = retval = fun(*args, **kwargs)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
site_worker_1     |     return self.run(*args, **kwargs)
site_worker_1     |   File "/app/src/apps/competitions/tasks.py", line 278, in _run_submission
site_worker_1     |     submission = qs.get(pk=submission_pk)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
site_worker_1     |     raise self.model.DoesNotExist(
site_worker_1     | competitions.models.Submission.DoesNotExist: Submission matching query does not exist.
site_worker_1     | [2023-07-06 10:49:59,530: ERROR/ForkPoolWorker-2] Task competitions.tasks._run_submission[82674dc3-75a1-4db0-b1b7-ec84466897d6] raised unexpected: DoesNotExist('Submission matching query does not exist.')
site_worker_1     | Traceback (most recent call last):
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
site_worker_1     |     R = retval = fun(*args, **kwargs)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
site_worker_1     |     return self.run(*args, **kwargs)
site_worker_1     |   File "/app/src/apps/competitions/tasks.py", line 278, in _run_submission
site_worker_1     |     submission = qs.get(pk=submission_pk)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
site_worker_1     |     raise self.model.DoesNotExist(
site_worker_1     | competitions.models.Submission.DoesNotExist: Submission matching query does not exist.
site_worker_1     | [2023-07-06 10:49:59,533: INFO/MainProcess] Received task: competitions.tasks._run_submission[53522b68-75ef-4dfd-9ef5-94b3105f2eef]  
site_worker_1     | [2023-07-06 10:49:59,535: INFO/MainProcess] Received task: competitions.tasks._run_submission[fd7fda6c-7535-4f86-9a2e-12b114e798aa]  
site_worker_1     | [2023-07-06 10:49:59,544: ERROR/ForkPoolWorker-3] Task competitions.tasks._run_submission[af7310ba-4334-42f7-a47f-6da017d0c373] raised unexpected: DoesNotExist('Submission matching query does not exist.')
site_worker_1     | Traceback (most recent call last):
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
site_worker_1     |     R = retval = fun(*args, **kwargs)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
site_worker_1     |     return self.run(*args, **kwargs)
site_worker_1     |   File "/app/src/apps/competitions/tasks.py", line 278, in _run_submission
site_worker_1     |     submission = qs.get(pk=submission_pk)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
site_worker_1     |     raise self.model.DoesNotExist(
site_worker_1     | competitions.models.Submission.DoesNotExist: Submission matching query does not exist.
site_worker_1     | [2023-07-06 10:49:59,548: ERROR/ForkPoolWorker-2] Task competitions.tasks._run_submission[4b083c13-8609-4859-b593-599d1a5644c6] raised unexpected: DoesNotExist('Submission matching query does not exist.')
site_worker_1     | Traceback (most recent call last):
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
site_worker_1     |     R = retval = fun(*args, **kwargs)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
site_worker_1     |     return self.run(*args, **kwargs)
site_worker_1     |   File "/app/src/apps/competitions/tasks.py", line 278, in _run_submission
site_worker_1     |     submission = qs.get(pk=submission_pk)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
site_worker_1     |     raise self.model.DoesNotExist(
site_worker_1     | competitions.models.Submission.DoesNotExist: Submission matching query does not exist.
site_worker_1     | [2023-07-06 10:49:59,560: ERROR/ForkPoolWorker-3] Task competitions.tasks._run_submission[53522b68-75ef-4dfd-9ef5-94b3105f2eef] raised unexpected: DoesNotExist('Submission matching query does not exist.')
site_worker_1     | Traceback (most recent call last):
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
site_worker_1     |     R = retval = fun(*args, **kwargs)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
site_worker_1     |     return self.run(*args, **kwargs)
site_worker_1     |   File "/app/src/apps/competitions/tasks.py", line 278, in _run_submission
site_worker_1     |     submission = qs.get(pk=submission_pk)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
site_worker_1     |     raise self.model.DoesNotExist(
site_worker_1     | competitions.models.Submission.DoesNotExist: Submission matching query does not exist.
site_worker_1     | [2023-07-06 10:49:59,562: ERROR/ForkPoolWorker-2] Task competitions.tasks._run_submission[fd7fda6c-7535-4f86-9a2e-12b114e798aa] raised unexpected: DoesNotExist('Submission matching query does not exist.')
site_worker_1     | Traceback (most recent call last):
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 382, in trace_task
site_worker_1     |     R = retval = fun(*args, **kwargs)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 641, in __protected_call__
site_worker_1     |     return self.run(*args, **kwargs)
site_worker_1     |   File "/app/src/apps/competitions/tasks.py", line 278, in _run_submission
site_worker_1     |     submission = qs.get(pk=submission_pk)
site_worker_1     |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
site_worker_1     |     raise self.model.DoesNotExist(
site_worker_1     | competitions.models.Submission.DoesNotExist: Submission matching query does not exist.
```

**Comment by spencrr** [comment]
1. I tried the edit button, but even looking at the network activity, I don't see any error message.
2. I have changed the tasks previously and there are most likely submissions made on tasks no longer part of the competition.

**Comment by Didayolo** [comment]
@dtuantran @ihsaan-ullah Any insights after reading the logs?

**Comment by ihsaan-ullah** [comment]
I am not sure why this is happening. It looks like when a task is updated, the following code is run

```python
File "/app/src/apps/competitions/tasks.py", line 278, in _run_submission
```

Is this suppose to happen? I am unable to reproduce this problem on my side. Is there a specific action done which lead to this problem?

If I can get a competition bundle which does this, then maybe I can check the logs locally and identify the real problem.  

In short, to me the problem seems to be not of changing tasks but of rerunning submissions which cannot be found or the submission leaderboard cannot be found. Still cannot figure out what triggers the rerunning of submissions

**Comment by ihsaan-ullah** [comment]
The error handling is also poor that's why we are not seeing error but just 500 status. I think this can be imporved later

**Comment by Didayolo** [comment]
> I am unable to reproduce this problem on my side. Is there a specific action done which lead to this problem?

The problem only happens in the following competition:

https://www.codabench.org/competitions/984/

When you change the tasks and try to save, nothing happens. I guess you can't reproduce it because you can't access the editor of this competition as you are not part of the organizers, and you are not part of the administrators of the platform. I forgot about this; maybe we should grant you the admin priviledges.

**Comment by Didayolo** [comment]
> If I can get a competition bundle which does this, then maybe I can check the logs locally and identify the real problem.

@spencrr If you re-upload your bundle, does the problem still happens?

**Comment by spencrr** [comment]
> I am not sure why this is happening. It looks like when a task is updated, the following code is run
> 
> ```python
> File "/app/src/apps/competitions/tasks.py", line 278, in _run_submission
> ```
> 
> Is this suppose to happen? I am unable to reproduce this problem on my side. Is there a specific action done which lead to this problem?
> 
> If I can get a competition bundle which does this, then maybe I can check the logs locally and identify the real problem.
> 
> In short, to me the problem seems to be not of changing tasks but of rerunning submissions which cannot be found or the submission leaderboard cannot be found. Still cannot figure out what triggers the rerunning of submissions

I have tried re-uploading, but am not able to reproduce the issue. The current bundle I have does **not** represent the current state of the competition (different version of the tasks/ingestion program/etc.). My theory is that this competition (984) has an error due to having submissions from different old versions of the tasks.

**Comment by Didayolo** [comment]
> My theory is that this competition (984) has an error due to having submissions from different old versions of the tasks.

But the new ingestion programs etc. are in used by different tasks, right? You can't edit a task right now, so the past submissions were done on different tasks than the one used right now, I guess. I need to think about it, the problem is quite misleading. Even if at some point you use a fresh competition, please do not delete this one as we need it to investigate the problem.

**Comment by ihsaan-ullah** [comment]
The problem starts from here:
https://github.com/codalab/codabench/blob/c49838331ed5f6500a8e768220d36e3d481ea08f/src/apps/api/views/competitions.py#L536

When you update a competition, this is called when you update the tasks
```python
def run_new_task_submissions(self, phase, tasks):
        tasks_ids = set([task.id for task in tasks])
        submissions = phase.submissions.filter(has_children=True).prefetch_related("children").all()

        for submission in submissions:
            child_tasks_ids = set(submission.children.values_list('task__id', flat=True))
            missing_tasks = tasks_ids - child_tasks_ids
            for task in filter(lambda t: t.id in missing_tasks, tasks):
                sub = Submission(
                    owner=submission.owner,
                    phase=submission.phase,
                    parent=submission,
                    task=task,
                    appear_on_leaderboards=submission.appear_on_leaderboards,
                    leaderboard=submission.children.first().leaderboard,
                    data=submission.data,
                )
                sub.save(ignore_submission_limit=True)
                sub.start(tasks=[task])
```

**Comment by ihsaan-ullah** [comment]
@Didayolo do we want to investigate this or close it for now?

**Comment by Didayolo** [comment]
Let's close it as it only happened once, on an old bundle.
